// One-off generator: freezes the current derived Module C programme into the
// flat node model under src/lib/content/. Run once from the repo root:
//
//   npx tsx front/scripts/snapshot-content.ts
//
// It runs the existing builder (program/index.ts + vocabSections.ts), reads the
// x/y and prerequisite chain it computes, and writes each lesson out as a
// standalone LessonNode — positions, prerequisites, codes and `big` frozen
// exactly as the canvas renders them today. After verifying the canvas is
// unchanged, the old builder can be deleted; this script goes with it.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { programContent, programSectionMeta } from '../src/lib/program/index.ts';
import { getRounds, type Lesson } from '../src/lib/sectionContent.ts';
import { isScreenEmpty, countQuestions } from '../src/lib/lesson-screens/types.ts';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '../src/lib/content');
const MODULE = 'c';

// Verbatim copy of isBigNode() from the canvas page — so the frozen `big`
// value matches exactly what the page computes today.
function isBigNode(lesson: Lesson): boolean {
	if (lesson.big !== undefined) return lesson.big;
	return getRounds(lesson)
		.flat()
		.filter((screen) => !isScreenEmpty(screen))
		.every((screen) => countQuestions(screen) === 0);
}

function jsonLiteral(value: unknown): string {
	return JSON.stringify(value, null, 2);
}

mkdirSync(join(OUT, 'c'), { recursive: true });

const sectionFileNames: string[] = [];

for (const meta of programSectionMeta) {
	const key = `${MODULE}-${meta.id}`;
	const section = programContent[key];
	const lessons = (section?.lessons ?? []).map((lesson, i) => ({
		id: lesson.id,
		section: key,
		titleHe: lesson.titleHe,
		code: `${MODULE}.${meta.id}.${lesson.code ?? i + 1}`,
		required: lesson.prerequisites ?? [],
		position: { x: lesson.x ?? 0, y: lesson.y ?? 0 },
		big: isBigNode(lesson),
		content: { rounds: getRounds(lesson).map((screens) => ({ screens })) }
	}));

	const varName = `c${meta.id}Lessons`;
	const file = `c-${meta.id}.ts`;
	sectionFileNames.push(file);
	writeFileSync(
		join(OUT, 'c', file),
		`// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.\n` +
			`import type { LessonNode } from '../types';\n\n` +
			`export const ${varName}: LessonNode[] = ${jsonLiteral(lessons)};\n`
	);
}

// sectionMeta.ts
const sectionMeta = programSectionMeta.map((meta) => {
	const intro = programContent[`${MODULE}-${meta.id}`]?.intro;
	return { id: `${MODULE}-${meta.id}`, titleHe: meta.titleHe, titleEn: meta.titleEn, intro };
});
writeFileSync(
	join(OUT, 'sectionMeta.ts'),
	`// Generated by scripts/snapshot-content.ts — section grouping for the path\n` +
		`// canvas (headings + theme-color order). Edit freely from here on.\n` +
		`import type { SectionMeta } from './types';\n\n` +
		`export const sectionMeta: SectionMeta[] = ${jsonLiteral(sectionMeta)};\n`
);

// index.ts
const imports = programSectionMeta
	.map((m) => `import { c${m.id}Lessons } from './c/c-${m.id}';`)
	.join('\n');
const spread = programSectionMeta.map((m) => `\t...c${m.id}Lessons`).join(',\n');
writeFileSync(
	join(OUT, 'index.ts'),
	`// Generated by scripts/snapshot-content.ts. Aggregates every section's\n` +
		`// LessonNode[] into one lookup. Add new sections to the imports + list below.\n` +
		`import type { LessonNode } from './types';\n${imports}\n\n` +
		`export * from './types';\nexport { sectionMeta } from './sectionMeta';\n\n` +
		`const all: LessonNode[] = [\n${spread}\n];\n\n` +
		`export const allLessons: Record<string, LessonNode> = Object.fromEntries(\n` +
		`\tall.map((lesson) => [lesson.id, lesson])\n);\n\n` +
		`export function getLesson(id: string): LessonNode | undefined {\n\treturn allLessons[id];\n}\n\n` +
		`export function getLessonsBySection(section: string): LessonNode[] {\n` +
		`\treturn all.filter((lesson) => lesson.section === section);\n}\n`
);

// types.ts
writeFileSync(
	join(OUT, 'types.ts'),
	`// The flat content model. One Lesson = one path node = one future DB row\n` +
		`// (see schema.sql). Screens keep the existing strict union so authoring\n` +
		`// and the runner share one type.\n` +
		`import type { LessonScreen } from '$lib/lesson-screens/types';\n\n` +
		`export type { LessonScreen };\n\n` +
		`export interface LessonRound {\n\tscreens: LessonScreen[];\n}\n\n` +
		`/** At least one round; round 0 is the main one, later rounds are optional practice. */\n` +
		`export interface LessonContent {\n\trounds: LessonRound[];\n}\n\n` +
		`export interface LessonNode {\n` +
		`\t/** Unique within the module; the join key for progress and \`required\`. */\n\tid: string;\n` +
		`\t/** Grouping key, matches a SectionMeta.id (e.g. 'c-4'). */\n\tsection: string;\n` +
		`\ttitleHe: string;\n\ttitleEn?: string;\n` +
		`\t/** Display code on the node label, e.g. 'c.4.2a'. */\n\tcode: string;\n` +
		`\t/** Lesson ids that must have round 1 done before this unlocks (AND'd). */\n\trequired: string[];\n` +
		`\t/** Canvas placement in px, relative to the path's horizontal center. */\n\tposition: { x: number; y: number };\n` +
		`\t/** Bigger node — no scored screen in any round. */\n\tbig: boolean;\n` +
		`\timage?: string;\n\tcontent: LessonContent;\n}\n\n` +
		`export interface SectionMeta {\n\tid: string;\n\ttitleHe: string;\n\ttitleEn?: string;\n` +
		`\tintro?: { greeting: string; goal?: string };\n}\n`
);

// schema.sql
writeFileSync(
	join(OUT, 'schema.sql'),
	`-- Supabase schema for the flat content model. Not wired up yet — a\n` +
		`-- LessonNode maps 1:1 onto a \`lessons\` row (content as JSONB).\n\n` +
		`create table lessons (\n` +
		`  id text primary key,\n  section text not null,\n  title_he text not null,\n` +
		`  title_en text,\n  code text not null,\n  required jsonb not null default '[]',\n` +
		`  position jsonb not null default '{"x":0,"y":0}',\n  big boolean not null default false,\n` +
		`  image_url text,\n  content jsonb not null\n);\n\n` +
		`create table lesson_progress (\n` +
		`  user_id uuid references auth.users(id) on delete cascade,\n` +
		`  lesson_id text references lessons(id) on delete cascade,\n` +
		`  rounds_done int not null default 0,\n  completed_at timestamptz,\n` +
		`  primary key (user_id, lesson_id)\n);\n`
);

console.log(
	`wrote ${sectionFileNames.length} section files + types/index/sectionMeta/schema to ${OUT}`
);
