// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c1Lessons: LessonNode[] = [
  {
    "id": "s1-l1",
    "section": "c-1",
    "titleHe": "חמש המילים שפותחות כל שאלה",
    "code": "c.1.1",
    "required": [],
    "position": {
      "x": 0,
      "y": 120
    },
    "big": false,
    "content": {
      "rounds": [
        {
          "screens": [
            {
              "type": "preface",
              "text": "בכל שאלה בשאלון C חוזרות אותן חמש מילים. הן לא קשות — אבל אם אתם עוצרים לחשוב עליהן באמצע הבחינה, איבדתם שניות שאין לכם. המטרה כאן היא לא להבין אותן, אלא לדעת אותן בלי לחשוב."
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"paragraph\"?",
              "options": [
                "פסקה",
                "משפט",
                "כותרת",
                "עמוד"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"according to\"?",
              "options": [
                "למרות",
                "לפי / על פי",
                "בגלל",
                "בניגוד ל־"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"explain / explains\"?",
              "options": [
                "לתאר",
                "לשאול",
                "להסביר / מסביר",
                "לתרגם"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"give ONE answer\"?",
              "options": [
                "תנו כמה דוגמאות",
                "הסבירו בהרחבה",
                "אל תענו",
                "תנו תשובה אחת בלבד"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"complete the sentence\"?",
              "options": [
                "השלימו את המשפט",
                "כתבו משפט חדש",
                "תקנו את השגיאה",
                "קצרו את המשפט"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "Read ______ II and answer the question.",
              "options": [
                "paragraph",
                "according to",
                "explain / explains",
                "give ONE answer"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "______ Dr. Klein, adults learn quickly.",
              "options": [
                "explain / explains",
                "according to",
                "give ONE answer",
                "complete the sentence"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "What does Dr. Klein ______ about adult swimmers?",
              "options": [
                "give ONE answer",
                "complete the sentence",
                "explain / explains",
                "paragraph"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "______ from paragraph II — not a list.",
              "options": [
                "complete the sentence",
                "paragraph",
                "according to",
                "give ONE answer"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "______: \"They could not ___.\"",
              "options": [
                "complete the sentence",
                "paragraph",
                "according to",
                "explain / explains"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"In paragraph II, the writer describes the study.\" — מה המשמעות של \"paragraph\" כאן?",
              "options": [
                "פסקה",
                "משפט",
                "כותרת",
                "עמוד"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"According to a recent survey, over 30% of adults cannot swim.\" — מה המשמעות של \"according to\" כאן?",
              "options": [
                "למרות",
                "לפי / על פי",
                "בגלל",
                "בניגוד ל־"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"Adults understand what the teacher explains.\" — מה המשמעות של \"explain / explains\" כאן?",
              "options": [
                "לתאר",
                "לשאול",
                "להסביר / מסביר",
                "לתרגם"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"Give ONE answer from paragraph II.\" — מה המשמעות של \"give ONE answer\" כאן?",
              "options": [
                "תנו כמה דוגמאות",
                "הסבירו בהרחבה",
                "אל תענו",
                "תנו תשובה אחת בלבד"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"Complete the sentence: They could not swim.\" — מה המשמעות של \"complete the sentence\" כאן?",
              "options": [
                "השלימו את המשפט",
                "כתבו משפט חדש",
                "תקנו את השגיאה",
                "קצרו את המשפט"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  },
  {
    "id": "s1-l2",
    "section": "c-1",
    "titleHe": "כל מילה — לאן היא שולחת אותי",
    "code": "c.1.2",
    "required": [
      "s1-l1"
    ],
    "position": {
      "x": 70,
      "y": 240
    },
    "big": false,
    "content": {
      "rounds": [
        {
          "screens": [
            {
              "type": "preface",
              "text": "תרגום לבד לא עוזר בבחינה. \"according to Dr. Klein\" לא אומר רק \"לפי דוקטור קליין\" — הוא אומר: לכו לפסקה שבה מופיע השם קליין, וקראו רק אותה.\n\nכל מילת שאלה היא הוראת ניווט. עכשיו נלמד את ההוראה של כל אחת."
            },
            {
              "type": "mcq",
              "prompt": "\"According to Dr. Klein...\" — מה עושים?",
              "options": [
                "הולכים לפסקה שבה מופיע קליין",
                "מחפשים מספר בטקסט",
                "עונים מהידע הכללי שלי"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"Read paragraph II and answer\" — מה עושים?",
              "options": [
                "קוראים את כל הטקסט מההתחלה",
                "קוראים את פסקה II בלבד",
                "קוראים את הפסקה האחרונה"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"How many trees did the charity plant?\" — מה מחפשים?",
              "options": [
                "את כל המספרים בטקסט",
                "את שם הארגון",
                "מספר שצמוד למילה trees"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"Give ONE answer\" — איך עונים?",
              "options": [
                "משפט אחד",
                "כל מה שמצאתי בפסקה",
                "רשימה של שלושה דברים"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"Complete the sentence: They could not...\" — מה עושים?",
              "options": [
                "כותבים משפט חדש משלי",
                "מוצאים את המשפט בטקסט וממשיכים אותו",
                "מתרגמים את המשפט לעברית"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"What does Dr. Klein explain?\" — מה מחפשים?",
              "options": [
                "סיכום של כל הפסקה",
                "את דעתי על מה שקליין אומר",
                "את מה שקליין אומר בטקסט"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"Which statement is NOT true?\" — מה מחפשים?",
              "options": [
                "את המשפט השגוי",
                "את המשפט הנכון",
                "את המשפט הארוך ביותר"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"What is the main idea of paragraph II?\" — מה מחפשים?",
              "options": [
                "את הפרט הכי מעניין בפסקה",
                "משפט שמכסה את כל הפסקה",
                "את המשפט האחרון בפסקה"
              ],
              "correctIndex": 1
            },
            {
              "type": "summary",
              "title": "כל מילה = פעולה",
              "lines": [
                "according to X ← לפסקה של X.",
                "paragraph II ← רק לשם.",
                "how many ← מספר שצמוד לשם העצם שבשאלה.",
                "give ONE answer ← משפט אחד.",
                "NOT ← מחפשים את השגוי."
              ]
            }
          ]
        }
      ]
    }
  }
];
