// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c10Lessons: LessonNode[] = [
  {
    "id": "s10-l1",
    "section": "c-10",
    "titleHe": "מילים: שאלות התייחסות",
    "code": "c.10.1",
    "required": [
      "s9-l1"
    ],
    "position": {
      "x": -100,
      "y": 1800
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "מילים לשאלות התייחסות — למה מתייחסת מילה, ומה נחקר."
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"refer(s) to\"?",
              "options": [
                "מתייחס ל־",
                "מתעלם מ־",
                "מוחק",
                "מסתיר"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"experiment\"?",
              "options": [
                "סיפור",
                "ניסוי",
                "דעה",
                "כותרת"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"similar\"?",
              "options": [
                "זהה",
                "הפוך",
                "דומה",
                "רחוק"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"intense\"?",
              "options": [
                "חלש",
                "קל",
                "איטי",
                "עז / חזק"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"claim(s)\"?",
              "options": [
                "טוען",
                "מוכיח",
                "מכחיש",
                "שואל"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "In line 4, the word 'it' ______ the study.",
              "options": [
                "refer(s) to",
                "experiment",
                "similar",
                "intense"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "The scientists ran a two-year ______.",
              "options": [
                "similar",
                "experiment",
                "intense",
                "claim(s)"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "The results were ______ to last year's.",
              "options": [
                "intense",
                "claim(s)",
                "similar",
                "refer(s) to"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "Seven minutes of ______ exercise is enough.",
              "options": [
                "claim(s)",
                "refer(s) to",
                "experiment",
                "intense"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "The writer ______ that the method always works.",
              "options": [
                "claim(s)",
                "refer(s) to",
                "experiment",
                "similar"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"The pronoun 'they' refers to the volunteers.\" — מה המשמעות של \"refer(s) to\" כאן?",
              "options": [
                "מתייחס ל־",
                "מתעלם מ־",
                "מוחק",
                "מסתיר"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"In the experiment, one group exercised daily.\" — מה המשמעות של \"experiment\" כאן?",
              "options": [
                "סיפור",
                "ניסוי",
                "דעה",
                "כותרת"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"Adults and children showed similar progress.\" — מה המשמעות של \"similar\" כאן?",
              "options": [
                "זהה",
                "הפוך",
                "דומה",
                "רחוק"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"The training was short but very intense.\" — מה המשמעות של \"intense\" כאן?",
              "options": [
                "חלש",
                "קל",
                "איטי",
                "עז / חזק"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"He claims the study is wrong, but shows no proof.\" — מה המשמעות של \"claim(s)\" כאן?",
              "options": [
                "טוען",
                "מוכיח",
                "מכחיש",
                "שואל"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
