// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c11Lessons: LessonNode[] = [
  {
    "id": "s11-l1",
    "section": "c-11",
    "titleHe": "מילים: שאלות הסקה",
    "code": "c.11.1",
    "required": [
      "s10-l1"
    ],
    "position": {
      "x": -70,
      "y": 2160
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "מילים לשאלות הסקה — מה נרמז, ומה חלש במחקר."
        },
        {
          "type": "word-card",
          "word": "imply / implies",
          "translationHe": "רומז"
        },
        {
          "type": "word-card",
          "word": "conclude",
          "translationHe": "להסיק"
        },
        {
          "type": "word-card",
          "word": "limitation(s)",
          "translationHe": "מגבלה / חיסרון"
        },
        {
          "type": "word-card",
          "word": "maintain",
          "translationHe": "לשמור על / להתמיד"
        },
        {
          "type": "word-card",
          "word": "challenge(s)",
          "translationHe": "אתגר / לערער על"
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"imply / implies\"?",
              "options": [
                "רומז",
                "אומר במפורש",
                "מכחיש",
                "מוכיח"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"conclude\"?",
              "options": [
                "להתחיל",
                "להסיק",
                "לשאול",
                "לפקפק"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"limitation(s)\"?",
              "options": [
                "יתרון",
                "מטרה",
                "מגבלה / חיסרון",
                "תוצאה"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"maintain\"?",
              "options": [
                "להפסיק",
                "לשכוח",
                "לאבד",
                "לשמור על / להתמיד"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"challenge(s)\"?",
              "options": [
                "אתגר / לערער על",
                "הוכחה",
                "הסכמה",
                "סיכום"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "The text does not say it, but it ______ that costs rose.",
              "options": [
                "imply / implies",
                "conclude",
                "limitation(s)",
                "maintain"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "From this we can ______ that sleep matters.",
              "options": [
                "limitation(s)",
                "conclude",
                "maintain",
                "challenge(s)"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "The study has one clear ______: it was too short.",
              "options": [
                "maintain",
                "challenge(s)",
                "limitation(s)",
                "imply / implies"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "Most people cannot ______ this routine for long.",
              "options": [
                "challenge(s)",
                "imply / implies",
                "conclude",
                "maintain"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "This finding ______ what experts believed for years.",
              "options": [
                "challenge(s)",
                "imply / implies",
                "conclude",
                "limitation(s)"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"The ending implies that the project will continue.\" — מה המשמעות של \"imply / implies\" כאן?",
              "options": [
                "רומז",
                "אומר במפורש",
                "מכחיש",
                "מוכיח"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"The researchers conclude that more study is needed.\" — מה המשמעות של \"conclude\" כאן?",
              "options": [
                "להתחיל",
                "להסיק",
                "לשאול",
                "לפקפק"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"Critics point to the limitations of the research.\" — מה המשמעות של \"limitation(s)\" כאן?",
              "options": [
                "יתרון",
                "מטרה",
                "מגבלה / חיסרון",
                "תוצאה"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"It is hard to maintain the habit after a month.\" — מה המשמעות של \"maintain\" כאן?",
              "options": [
                "להפסיק",
                "לשכוח",
                "לאבד",
                "לשמור על / להתמיד"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"The new data challenges the old theory.\" — מה המשמעות של \"challenge(s)\" כאן?",
              "options": [
                "אתגר / לערער על",
                "הוכחה",
                "הסכמה",
                "סיכום"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
