// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c12Lessons: LessonNode[] = [
  {
    "id": "s12-l1",
    "section": "c-12",
    "titleHe": "מילים: הרעיון המרכזי",
    "code": "c.12.1",
    "required": [
      "s11-l1"
    ],
    "position": {
      "x": 0,
      "y": 2040
    },
    "big": false,
    "content": {
      "rounds": [
        {
          "screens": [
            {
              "type": "preface",
              "text": "מילים לשאלות רעיון מרכזי — הרס, אזהרה וחומרה."
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"destroy / destruction\"?",
              "options": [
                "הורס / הרס",
                "בונה",
                "שומר",
                "מתקן"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"cause(s)\"?",
              "options": [
                "תוצאה",
                "גורם / סיבה",
                "פתרון",
                "מטרה"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"warn(s)\"?",
              "options": [
                "מבטיח",
                "מרגיע",
                "מזהיר",
                "מכחיש"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"severe\"?",
              "options": [
                "קל",
                "נעים",
                "זמני",
                "חמור / קשה"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"individual\"?",
              "options": [
                "יחיד / אדם בודד",
                "קבוצה",
                "ממשלה",
                "חברה"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "Fires ______ large areas of forest every year.",
              "options": [
                "destroy / destruction",
                "cause(s)",
                "warn(s)",
                "severe"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "Farming is the main ______ of deforestation.",
              "options": [
                "warn(s)",
                "cause(s)",
                "severe",
                "individual"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "Scientists ______ that the situation is getting worse.",
              "options": [
                "severe",
                "individual",
                "warn(s)",
                "destroy / destruction"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "The region now faces more ______ droughts.",
              "options": [
                "individual",
                "destroy / destruction",
                "cause(s)",
                "severe"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "Every ______ can help by using less plastic.",
              "options": [
                "individual",
                "destroy / destruction",
                "cause(s)",
                "warn(s)"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"The destruction of the forest happened very fast.\" — מה המשמעות של \"destroy / destruction\" כאן?",
              "options": [
                "הורס / הרס",
                "בונה",
                "שומר",
                "מתקן"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"Cutting trees causes soil to wash away.\" — מה המשמעות של \"cause(s)\" כאן?",
              "options": [
                "תוצאה",
                "גורם / סיבה",
                "פתרון",
                "מטרה"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"Dr. Diallo warns that the forests may not recover.\" — מה המשמעות של \"warn(s)\" כאן?",
              "options": [
                "מבטיח",
                "מרגיע",
                "מזהיר",
                "מכחיש"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"The damage was severe and hard to repair.\" — מה המשמעות של \"severe\" כאן?",
              "options": [
                "קל",
                "נעים",
                "זמני",
                "חמור / קשה"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"One individual cannot fix the problem alone.\" — מה המשמעות של \"individual\" כאן?",
              "options": [
                "יחיד / אדם בודד",
                "קבוצה",
                "ממשלה",
                "חברה"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
