// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c13Lessons: LessonNode[] = [
  {
    "id": "s13-l1",
    "section": "c-13",
    "titleHe": "מילים: עמדת הכותב",
    "code": "c.13.1",
    "required": [
      "s12-l1"
    ],
    "position": {
      "x": 70,
      "y": 2160
    },
    "big": false,
    "content": {
      "rounds": [
        {
          "screens": [
            {
              "type": "preface",
              "text": "מילים שמגלות את עמדת הכותב — דאגה, הקלה וזהירות."
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"unfortunately\"?",
              "options": [
                "לרוע המזל / למרבה הצער",
                "למרבה השמחה",
                "במקרה",
                "בוודאי"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"fortunately\"?",
              "options": [
                "למרבה הצער",
                "למרבה המזל",
                "במקרה",
                "לבסוף"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"concerned\"?",
              "options": [
                "רגוע",
                "אדיש",
                "מודאג",
                "מרוצה"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"argue\"?",
              "options": [
                "להסכים",
                "לשתוק",
                "לתאר",
                "לטעון / לצדד"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"cautiously\"?",
              "options": [
                "בזהירות",
                "בביטחון מלא",
                "בפזיזות",
                "באדישות"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "______, many forests are disappearing fast.",
              "options": [
                "unfortunately",
                "fortunately",
                "concerned",
                "argue"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "______, some governments have started to act.",
              "options": [
                "concerned",
                "fortunately",
                "argue",
                "cautiously"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "Scientists are deeply ______ about the change.",
              "options": [
                "argue",
                "cautiously",
                "concerned",
                "unfortunately"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "The writer ______ strongly that change is needed.",
              "options": [
                "cautiously",
                "unfortunately",
                "fortunately",
                "argue"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "Experts are ______ optimistic about the results.",
              "options": [
                "cautiously",
                "unfortunately",
                "fortunately",
                "concerned"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"Unfortunately, the plan did not work as hoped.\" — מה המשמעות של \"unfortunately\" כאן?",
              "options": [
                "לרוע המזל / למרבה הצער",
                "למרבה השמחה",
                "במקרה",
                "בוודאי"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"Fortunately, the fire was stopped in time.\" — מה המשמעות של \"fortunately\" כאן?",
              "options": [
                "למרבה הצער",
                "למרבה המזל",
                "במקרה",
                "לבסוף"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"Parents are concerned about screen time.\" — מה המשמעות של \"concerned\" כאן?",
              "options": [
                "רגוע",
                "אדיש",
                "מודאג",
                "מרוצה"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"She argues that schools must do more.\" — מה המשמעות של \"argue\" כאן?",
              "options": [
                "להסכים",
                "לשתוק",
                "לתאר",
                "לטעון / לצדד"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"He answered cautiously, not sure of the facts.\" — מה המשמעות של \"cautiously\" כאן?",
              "options": [
                "בזהירות",
                "בביטחון מלא",
                "בפזיזות",
                "באדישות"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
