// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c14Lessons: LessonNode[] = [
  {
    "id": "s14-l1",
    "section": "c-14",
    "titleHe": "מילים: אוצר מילים — חברה",
    "code": "c.14.1",
    "required": [
      "s13-l1"
    ],
    "position": {
      "x": 100,
      "y": 2280
    },
    "big": false,
    "content": {
      "rounds": [
        {
          "screens": [
            {
              "type": "preface",
              "text": "אוצר מילים לנושאים חברתיים — מתנדבים, קהילה והזדמנויות."
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"community\"?",
              "options": [
                "קהילה",
                "ממשלה",
                "כיתה",
                "מדינה"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"volunteer\"?",
              "options": [
                "עובד בשכר",
                "מתנדב / להתנדב",
                "מנהל",
                "מבקר"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"responsible\"?",
              "options": [
                "תלותי",
                "מפוזר",
                "אחראי",
                "עצל"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"programme\"?",
              "options": [
                "סרט",
                "כרטיס",
                "פרס",
                "תוכנית"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"opportunity\"?",
              "options": [
                "הזדמנות",
                "בעיה",
                "חובה",
                "סכנה"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "The local ______ came together to help.",
              "options": [
                "community",
                "volunteer",
                "responsible",
                "programme"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "She ______ at the hospital twice a week.",
              "options": [
                "responsible",
                "volunteer",
                "programme",
                "opportunity"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "Work makes young people more ______.",
              "options": [
                "programme",
                "opportunity",
                "responsible",
                "community"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "The training ______ lasted two years.",
              "options": [
                "opportunity",
                "community",
                "volunteer",
                "programme"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "Volunteering is a great ______ to learn.",
              "options": [
                "opportunity",
                "community",
                "volunteer",
                "responsible"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"The community centre offers free classes.\" — מה המשמעות של \"community\" כאן?",
              "options": [
                "קהילה",
                "ממשלה",
                "כיתה",
                "מדינה"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"As a volunteer, he helps children read.\" — מה המשמעות של \"volunteer\" כאן?",
              "options": [
                "עובד בשכר",
                "מתנדב / להתנדב",
                "מנהל",
                "מבקר"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"Each student is responsible for one task.\" — מה המשמעות של \"responsible\" כאן?",
              "options": [
                "תלותי",
                "מפוזר",
                "אחראי",
                "עצל"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"The after-school programme helps with homework.\" — מה המשמעות של \"programme\" כאן?",
              "options": [
                "סרט",
                "כרטיס",
                "פרס",
                "תוכנית"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"This job is an opportunity to gain experience.\" — מה המשמעות של \"opportunity\" כאן?",
              "options": [
                "הזדמנות",
                "בעיה",
                "חובה",
                "סכנה"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
