// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c15Lessons: LessonNode[] = [
  {
    "id": "s15-l1",
    "section": "c-15",
    "titleHe": "מילים: אוצר מילים — טכנולוגיה וסביבה",
    "code": "c.15.1",
    "required": [
      "s14-l1"
    ],
    "position": {
      "x": 70,
      "y": 2640
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "אוצר מילים לנושאי טכנולוגיה וסביבה."
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"research\"?",
              "options": [
                "מחקר",
                "סקר קצר",
                "דעה",
                "סיפור"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"technology\"?",
              "options": [
                "טבע",
                "טכנולוגיה",
                "אמנות",
                "היסטוריה"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"environment\"?",
              "options": [
                "כלכלה",
                "ממשלה",
                "סביבה",
                "תרבות"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"affect / effect\"?",
              "options": [
                "מונע",
                "מודד",
                "מסתיר",
                "משפיע / השפעה"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"prevent\"?",
              "options": [
                "למנוע",
                "לגרום",
                "לעודד",
                "לזרז"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "New ______ shows that sleep affects memory.",
              "options": [
                "research",
                "technology",
                "environment",
                "affect / effect"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "New ______ is changing the way we work.",
              "options": [
                "environment",
                "technology",
                "affect / effect",
                "prevent"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "We must protect the ______ for the future.",
              "options": [
                "affect / effect",
                "prevent",
                "environment",
                "research"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "Pollution can ______ people's health.",
              "options": [
                "prevent",
                "research",
                "technology",
                "affect / effect"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "Exercise can ______ many health problems.",
              "options": [
                "prevent",
                "research",
                "technology",
                "environment"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"The research took three years to complete.\" — מה המשמעות של \"research\" כאן?",
              "options": [
                "מחקר",
                "סקר קצר",
                "דעה",
                "סיפור"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"Modern technology makes learning easier.\" — מה המשמעות של \"technology\" כאן?",
              "options": [
                "טבע",
                "טכנולוגיה",
                "אמנות",
                "היסטוריה"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"The factory harmed the local environment.\" — מה המשמעות של \"environment\" כאן?",
              "options": [
                "כלכלה",
                "ממשלה",
                "סביבה",
                "תרבות"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"Noise affects sleep, and the effect is serious.\" — מה המשמעות של \"affect / effect\" כאן?",
              "options": [
                "מונע",
                "מודד",
                "מסתיר",
                "משפיע / השפעה"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"The new rule was made to prevent accidents.\" — מה המשמעות של \"prevent\" כאן?",
              "options": [
                "למנוע",
                "לגרום",
                "לעודד",
                "לזרז"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
