// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c16Lessons: LessonNode[] = [
  {
    "id": "s16-l1",
    "section": "c-16",
    "titleHe": "מילים: מילים לכתיבה",
    "code": "c.16.1",
    "required": [
      "s15-l1"
    ],
    "position": {
      "x": 0,
      "y": 2760
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "מילים שימושיות לכתיבת חיבור — לנימוק ולביסוס."
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"volunteer\"?",
              "options": [
                "להתנדב / מתנדב",
                "לעבוד בשכר",
                "לנוח",
                "לבקר"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"benefit\"?",
              "options": [
                "חיסרון",
                "יתרון / תועלת",
                "מחיר",
                "סכנה"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"effective\"?",
              "options": [
                "יקר",
                "איטי",
                "יעיל",
                "מיותר"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"according to\"?",
              "options": [
                "בניגוד ל־",
                "למרות",
                "במקום",
                "לפי / על פי"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"responsible\"?",
              "options": [
                "אחראי",
                "תלותי",
                "עצל",
                "מפוזר"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "Many young people ______ in their free time.",
              "options": [
                "volunteer",
                "benefit",
                "effective",
                "according to"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "One ______ of working is earning your own money.",
              "options": [
                "effective",
                "benefit",
                "according to",
                "responsible"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "An ______ way to improve is to practise daily.",
              "options": [
                "according to",
                "responsible",
                "effective",
                "volunteer"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "______ many experts, experience matters most.",
              "options": [
                "responsible",
                "volunteer",
                "benefit",
                "according to"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "Work teaches us to be ______.",
              "options": [
                "responsible",
                "volunteer",
                "benefit",
                "effective"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"Volunteering helps me develop useful skills.\" — מה המשמעות של \"volunteer\" כאן?",
              "options": [
                "להתנדב / מתנדב",
                "לעבוד בשכר",
                "לנוח",
                "לבקר"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"The benefits of reading are clear.\" — מה המשמעות של \"benefit\" כאן?",
              "options": [
                "חיסרון",
                "יתרון / תועלת",
                "מחיר",
                "סכנה"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"The most effective method is regular practice.\" — מה המשמעות של \"effective\" כאן?",
              "options": [
                "יקר",
                "איטי",
                "יעיל",
                "מיותר"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"According to researchers, teenagers need more sleep.\" — מה המשמעות של \"according to\" כאן?",
              "options": [
                "בניגוד ל־",
                "למרות",
                "במקום",
                "לפי / על פי"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"Being responsible means doing what you promised.\" — מה המשמעות של \"responsible\" כאן?",
              "options": [
                "אחראי",
                "תלותי",
                "עצל",
                "מפוזר"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
