// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c17Lessons: LessonNode[] = [
  {
    "id": "s17-l1",
    "section": "c-17",
    "titleHe": "מילים: משפטים שעובדים",
    "code": "c.17.1",
    "required": [
      "s16-l1"
    ],
    "position": {
      "x": -70,
      "y": 2640
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "מבנים שפותחים ומחברים משפטים בחיבור דעה."
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"I think / I believe\"?",
              "options": [
                "אני חושב/ת / אני מאמין/ה",
                "אני יודע בוודאות",
                "אחרים חושבים",
                "ייתכן ש־"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"because\"?",
              "options": [
                "למרות ש־",
                "כי / מכיוון ש־",
                "לכן",
                "לדוגמה"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"for example\"?",
              "options": [
                "לסיכום",
                "לעומת זאת",
                "לדוגמה",
                "בנוסף"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"in addition / also\"?",
              "options": [
                "לעומת זאת",
                "לכן",
                "לבסוף",
                "בנוסף / גם"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"in conclusion\"?",
              "options": [
                "לסיכום",
                "ראשית",
                "לדוגמה",
                "אולם"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "______ that all pupils should do volunteer work.",
              "options": [
                "I think / I believe",
                "because",
                "for example",
                "in addition / also"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "Volunteering is good ______ it teaches responsibility.",
              "options": [
                "for example",
                "because",
                "in addition / also",
                "in conclusion"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "Many students help others. ______, they visit the elderly.",
              "options": [
                "in addition / also",
                "in conclusion",
                "for example",
                "I think / I believe"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "It builds skills. ______, it looks good on a CV.",
              "options": [
                "in conclusion",
                "I think / I believe",
                "because",
                "in addition / also"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "______, I believe the benefits are clear.",
              "options": [
                "in conclusion",
                "I think / I believe",
                "because",
                "for example"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"I believe that reading is the best way to learn English.\" — מה המשמעות של \"I think / I believe\" כאן?",
              "options": [
                "אני חושב/ת / אני מאמין/ה",
                "אני יודע בוודאות",
                "אחרים חושבים",
                "ייתכן ש־"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"I agree, because working builds confidence.\" — מה המשמעות של \"because\" כאן?",
              "options": [
                "למרות ש־",
                "כי / מכיוון ש־",
                "לכן",
                "לדוגמה"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"For example, a teenager who works learns time management.\" — מה המשמעות של \"for example\" כאן?",
              "options": [
                "לסיכום",
                "לעומת זאת",
                "לדוגמה",
                "בנוסף"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"In addition, volunteering helps you meet new people.\" — מה המשמעות של \"in addition / also\" כאן?",
              "options": [
                "לעומת זאת",
                "לכן",
                "לבסוף",
                "בנוסף / גם"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"In conclusion, every teenager should try volunteering.\" — מה המשמעות של \"in conclusion\" כאן?",
              "options": [
                "לסיכום",
                "ראשית",
                "לדוגמה",
                "אולם"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
