// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c18Lessons: LessonNode[] = [
  {
    "id": "s18-l1",
    "section": "c-18",
    "titleHe": "מילים: מילות קישור",
    "code": "c.18.1",
    "required": [
      "s17-l1"
    ],
    "position": {
      "x": -100,
      "y": 2760
    },
    "big": false,
    "content": {
      "rounds": [
        {
          "screens": [
            {
              "type": "preface",
              "text": "מילות קישור נפוצות — ושגיאות שכדאי להימנע מהן."
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"because\"?",
              "options": [
                "כי / מכיוון ש־",
                "אבל",
                "לכן",
                "כלומר"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"however\"?",
              "options": [
                "לכן",
                "אולם / אבל",
                "לדוגמה",
                "מכיוון ש־"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"for example\"?",
              "options": [
                "לסיכום",
                "אולם",
                "לדוגמה",
                "בנוסף"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"in addition / also\"?",
              "options": [
                "אולם",
                "לכן",
                "לבסוף",
                "בנוסף / גם"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"although\"?",
              "options": [
                "למרות ש־",
                "מכיוון ש־",
                "לכן",
                "לדוגמה"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "I support it ______ it helps the community.",
              "options": [
                "because",
                "however",
                "for example",
                "in addition / also"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "The idea is good. ______, it costs a lot of money.",
              "options": [
                "for example",
                "however",
                "in addition / also",
                "although"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "Some jobs teach real skills — ______, working in a shop.",
              "options": [
                "in addition / also",
                "although",
                "for example",
                "because"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "It builds confidence. ______, it teaches teamwork.",
              "options": [
                "although",
                "because",
                "however",
                "in addition / also"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "______ the work was hard, the students enjoyed it.",
              "options": [
                "although",
                "because",
                "however",
                "for example"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"She stayed home because she was ill.\" — מה המשמעות של \"because\" כאן?",
              "options": [
                "כי / מכיוון ש־",
                "אבל",
                "לכן",
                "כלומר"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"However, not everyone agrees with the plan.\" — מה המשמעות של \"however\" כאן?",
              "options": [
                "לכן",
                "אולם / אבל",
                "לדוגמה",
                "מכיוון ש־"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"For example, many students volunteer once a week.\" — מה המשמעות של \"for example\" כאן?",
              "options": [
                "לסיכום",
                "אולם",
                "לדוגמה",
                "בנוסף"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"In addition, the programme is completely free.\" — מה המשמעות של \"in addition / also\" כאן?",
              "options": [
                "אולם",
                "לכן",
                "לבסוף",
                "בנוסף / גם"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"Although it rained, the event went ahead.\" — מה המשמעות של \"although\" כאן?",
              "options": [
                "למרות ש־",
                "מכיוון ש־",
                "לכן",
                "לדוגמה"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
