// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c19Lessons: LessonNode[] = [
  {
    "id": "s19-l1",
    "section": "c-19",
    "titleHe": "מילים: ניהול זמן",
    "code": "c.19.1",
    "required": [
      "s18-l1"
    ],
    "position": {
      "x": -70,
      "y": 3120
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "מילות הוראה שצריך לזהות מייד — כדי לא לבזבז זמן במבחן."
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"paragraph\"?",
              "options": [
                "פסקה",
                "משפט",
                "עמוד",
                "כותרת"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"according to\"?",
              "options": [
                "בניגוד ל־",
                "לפי / על פי",
                "למרות",
                "לפני"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"complete\"?",
              "options": [
                "להתחיל",
                "למחוק",
                "להשלים",
                "לקצר"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"give ONE answer\"?",
              "options": [
                "תנו שתי תשובות",
                "תנו דוגמה",
                "אל תענו",
                "תנו תשובה אחת בלבד"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"put a √ by the TWO\"?",
              "options": [
                "סמנו √ ליד השתיים",
                "סמנו אחת",
                "סמנו הכל",
                "אל תסמנו"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "Read ______ III before you answer.",
              "options": [
                "paragraph",
                "according to",
                "complete",
                "give ONE answer"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "______ the researcher, the effect was small.",
              "options": [
                "complete",
                "according to",
                "give ONE answer",
                "put a √ by the TWO"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "______ the sentence with words from the text.",
              "options": [
                "give ONE answer",
                "put a √ by the TWO",
                "complete",
                "paragraph"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "______ — do not write a list.",
              "options": [
                "put a √ by the TWO",
                "paragraph",
                "according to",
                "give ONE answer"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "______ correct statements.",
              "options": [
                "put a √ by the TWO",
                "paragraph",
                "according to",
                "complete"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"The answer is in paragraph II, near the end.\" — מה המשמעות של \"paragraph\" כאן?",
              "options": [
                "פסקה",
                "משפט",
                "עמוד",
                "כותרת"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"According to the text, the study lasted a year.\" — מה המשמעות של \"according to\" כאן?",
              "options": [
                "בניגוד ל־",
                "לפי / על פי",
                "למרות",
                "לפני"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"Complete the missing part using the passage.\" — מה המשמעות של \"complete\" כאן?",
              "options": [
                "להתחיל",
                "למחוק",
                "להשלים",
                "לקצר"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"Give ONE answer, taken from paragraph III.\" — מה המשמעות של \"give ONE answer\" כאן?",
              "options": [
                "תנו שתי תשובות",
                "תנו דוגמה",
                "אל תענו",
                "תנו תשובה אחת בלבד"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"Put a √ by the TWO answers that match the text.\" — מה המשמעות של \"put a √ by the TWO\" כאן?",
              "options": [
                "סמנו √ ליד השתיים",
                "סמנו אחת",
                "סמנו הכל",
                "אל תסמנו"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
