// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c2Lessons: LessonNode[] = [
  {
    "id": "s2-l1",
    "section": "c-2",
    "titleHe": "מילים: קריאה אסטרטגית",
    "code": "c.2.1",
    "required": [
      "s1-l2"
    ],
    "position": {
      "x": 100,
      "y": 360
    },
    "big": false,
    "content": {
      "rounds": [
        {
          "screens": [
            {
              "type": "preface",
              "text": "חמש מילים שמופיעות כמעט בכל הוראה בשאלון C. בלעדיהן קשה להבין מה השאלה מבקשת."
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"paragraph\"?",
              "options": [
                "פסקה",
                "משפט",
                "כותרת",
                "עמוד"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"according to\"?",
              "options": [
                "בניגוד ל־",
                "לפי / על פי",
                "למרות",
                "בזכות"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"explain / explains\"?",
              "options": [
                "לשאול",
                "לתרגם",
                "להסביר / מסביר",
                "לספור"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"give ONE answer\"?",
              "options": [
                "תנו כמה תשובות",
                "תנו דוגמה",
                "אל תענו",
                "תנו תשובה אחת בלבד"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"complete the sentence\"?",
              "options": [
                "השלימו את המשפט",
                "כתבו משפט חדש",
                "תקנו שגיאה",
                "קצרו את המשפט"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "Read the second ______ and answer the question.",
              "options": [
                "paragraph",
                "according to",
                "explain / explains",
                "give ONE answer"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "______ the text, the study lasted two months.",
              "options": [
                "explain / explains",
                "according to",
                "give ONE answer",
                "complete the sentence"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "Question 3 asks you to ______ why prices rose.",
              "options": [
                "give ONE answer",
                "complete the sentence",
                "explain / explains",
                "paragraph"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "______ from paragraph III — not a list.",
              "options": [
                "complete the sentence",
                "paragraph",
                "according to",
                "give ONE answer"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "______: \"They could not ___.\"",
              "options": [
                "complete the sentence",
                "paragraph",
                "according to",
                "explain / explains"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"In paragraph II, the writer describes the study.\" — מה המשמעות של \"paragraph\" כאן?",
              "options": [
                "פסקה",
                "משפט",
                "כותרת",
                "עמוד"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"According to Dr. Klein, adults learn quickly.\" — מה המשמעות של \"according to\" כאן?",
              "options": [
                "בניגוד ל־",
                "לפי / על פי",
                "למרות",
                "בזכות"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"The article explains how the system works.\" — מה המשמעות של \"explain / explains\" כאן?",
              "options": [
                "לשאול",
                "לתרגם",
                "להסביר / מסביר",
                "לספור"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"Give ONE answer, in a full sentence.\" — מה המשמעות של \"give ONE answer\" כאן?",
              "options": [
                "תנו כמה תשובות",
                "תנו דוגמה",
                "אל תענו",
                "תנו תשובה אחת בלבד"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"Complete the sentence using words from the text.\" — מה המשמעות של \"complete the sentence\" כאן?",
              "options": [
                "השלימו את המשפט",
                "כתבו משפט חדש",
                "תקנו שגיאה",
                "קצרו את המשפט"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
