// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c20Lessons: LessonNode[] = [
  {
    "id": "s20-l1",
    "section": "c-20",
    "titleHe": "מילים: אתגר מתוזמן",
    "code": "c.20.1",
    "required": [
      "s19-l1"
    ],
    "position": {
      "x": 0,
      "y": 3000
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "הוראות מפתח לתרגול מתוזמן — לזהות מהר ולפעול."
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"according to\"?",
              "options": [
                "לפי / על פי",
                "בניגוד ל־",
                "למרות",
                "במקום"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"explain(s)\"?",
              "options": [
                "שואל",
                "מסביר",
                "מתרגם",
                "מונה"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"complete\"?",
              "options": [
                "להתחיל",
                "לתקן",
                "להשלים",
                "לקצר"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"two correct\"?",
              "options": [
                "תשובה אחת נכונה",
                "אין תשובה נכונה",
                "שלוש נכונות",
                "שתי תשובות נכונות"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"not\"?",
              "options": [
                "לא / שלילה",
                "כן",
                "אולי",
                "תמיד"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "______ Dr. Tanaka, apps cannot replace people.",
              "options": [
                "according to",
                "explain(s)",
                "complete",
                "two correct"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "Question 2 asks what the writer ______.",
              "options": [
                "complete",
                "explain(s)",
                "two correct",
                "not"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "______ the sentence: \"They could not ___.\"",
              "options": [
                "two correct",
                "not",
                "complete",
                "according to"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "Mark the ______ answers, not just one.",
              "options": [
                "not",
                "according to",
                "explain(s)",
                "two correct"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "Which statement is ______ true according to the text?",
              "options": [
                "not",
                "according to",
                "explain(s)",
                "complete"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"According to the study, most learners are adults.\" — מה המשמעות של \"according to\" כאן?",
              "options": [
                "לפי / על פי",
                "בניגוד ל־",
                "למרות",
                "במקום"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"The text explains why the plan failed.\" — מה המשמעות של \"explain(s)\" כאן?",
              "options": [
                "שואל",
                "מסביר",
                "מתרגם",
                "מונה"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"Complete the answer with two or three words.\" — מה המשמעות של \"complete\" כאן?",
              "options": [
                "להתחיל",
                "לתקן",
                "להשלים",
                "לקצר"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"There are two correct options in this question.\" — מה המשמעות של \"two correct\" כאן?",
              "options": [
                "תשובה אחת נכונה",
                "אין תשובה נכונה",
                "שלוש נכונות",
                "שתי תשובות נכונות"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"The question asks which detail is NOT mentioned.\" — מה המשמעות של \"not\" כאן?",
              "options": [
                "לא / שלילה",
                "כן",
                "אולי",
                "תמיד"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
