// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c21Lessons: LessonNode[] = [
  {
    "id": "s21-l1",
    "section": "c-21",
    "titleHe": "מילים: שאלות כן/לא",
    "code": "c.21.1",
    "required": [
      "s20-l1"
    ],
    "position": {
      "x": 70,
      "y": 3360
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "מבנים לפתיחת עמדה בשאלת כן/לא בחיבור."
        },
        {
          "type": "word-card",
          "word": "I think / I believe",
          "translationHe": "אני חושב/ת / אני מאמין/ה"
        },
        {
          "type": "word-card",
          "word": "In my opinion",
          "translationHe": "לדעתי"
        },
        {
          "type": "word-card",
          "word": "because",
          "translationHe": "כי / מכיוון ש־"
        },
        {
          "type": "word-card",
          "word": "important",
          "translationHe": "חשוב"
        },
        {
          "type": "word-card",
          "word": "agree / disagree",
          "translationHe": "מסכים / לא מסכים"
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"I think / I believe\"?",
              "options": [
                "אני חושב/ת / אני מאמין/ה",
                "כולם חושבים",
                "ידוע ש־",
                "ספק אם"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"In my opinion\"?",
              "options": [
                "לדעת כולם",
                "לדעתי",
                "בעובדה",
                "אולי"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"because\"?",
              "options": [
                "אבל",
                "למרות",
                "כי / מכיוון ש־",
                "לכן"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"important\"?",
              "options": [
                "מיותר",
                "קל",
                "זול",
                "חשוב"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"agree / disagree\"?",
              "options": [
                "מסכים / לא מסכים",
                "שואל",
                "שוכח",
                "מתאר"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "______ that school days are too long.",
              "options": [
                "I think / I believe",
                "In my opinion",
                "because",
                "important"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "______, tests are held too often.",
              "options": [
                "because",
                "In my opinion",
                "important",
                "agree / disagree"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "I disagree ______ the plan is too expensive.",
              "options": [
                "important",
                "agree / disagree",
                "because",
                "I think / I believe"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "It is ______ for teenagers to have free time.",
              "options": [
                "agree / disagree",
                "I think / I believe",
                "In my opinion",
                "important"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "I ______ with the idea that phones help learning.",
              "options": [
                "agree / disagree",
                "I think / I believe",
                "In my opinion",
                "because"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"I think that every teenager should learn to cook.\" — מה המשמעות של \"I think / I believe\" כאן?",
              "options": [
                "אני חושב/ת / אני מאמין/ה",
                "כולם חושבים",
                "ידוע ש־",
                "ספק אם"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"In my opinion, homework should be shorter.\" — מה המשמעות של \"In my opinion\" כאן?",
              "options": [
                "לדעת כולם",
                "לדעתי",
                "בעובדה",
                "אולי"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"I agree, because it gives students real experience.\" — מה המשמעות של \"because\" כאן?",
              "options": [
                "אבל",
                "למרות",
                "כי / מכיוון ש־",
                "לכן"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"It is important to start every opinion clearly.\" — מה המשמעות של \"important\" כאן?",
              "options": [
                "מיותר",
                "קל",
                "זול",
                "חשוב"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"I disagree with the statement in the prompt.\" — מה המשמעות של \"agree / disagree\" כאן?",
              "options": [
                "מסכים / לא מסכים",
                "שואל",
                "שוכח",
                "מתאר"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
