// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c22Lessons: LessonNode[] = [
  {
    "id": "s22-l1",
    "section": "c-22",
    "titleHe": "מילים: נימוק, הסבר ודוגמה",
    "code": "c.22.1",
    "required": [
      "s21-l1"
    ],
    "position": {
      "x": 100,
      "y": 3240
    },
    "big": false,
    "content": {
      "rounds": [
        {
          "screens": [
            {
              "type": "preface",
              "text": "מבנים לבניית פסקת נימוק מסודרת: נימוק ← הסבר ← דוגמה."
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"reason\"?",
              "options": [
                "סיבה / נימוק",
                "תוצאה",
                "דוגמה",
                "סיכום"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"this means\"?",
              "options": [
                "למרות זאת",
                "כלומר / זאת אומרת",
                "לדוגמה",
                "לסיכום"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"for example\"?",
              "options": [
                "לסיכום",
                "אולם",
                "לדוגמה",
                "ראשית"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"therefore\"?",
              "options": [
                "למרות זאת",
                "לדוגמה",
                "מכיוון ש־",
                "לכן / לפיכך"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"another reason\"?",
              "options": [
                "סיבה נוספת",
                "אותה סיבה",
                "ללא סיבה",
                "הסיבה היחידה"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "One ______ to volunteer is that it builds skills.",
              "options": [
                "reason",
                "this means",
                "for example",
                "therefore"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "Students practise daily. ______, they improve fast.",
              "options": [
                "for example",
                "this means",
                "therefore",
                "another reason"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "Work teaches skills — ______, how to manage money.",
              "options": [
                "therefore",
                "another reason",
                "for example",
                "reason"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "It builds confidence. ______, I support it.",
              "options": [
                "another reason",
                "reason",
                "this means",
                "therefore"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "______ is that it helps the community.",
              "options": [
                "another reason",
                "reason",
                "this means",
                "for example"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"The main reason is that it teaches responsibility.\" — מה המשמעות של \"reason\" כאן?",
              "options": [
                "סיבה / נימוק",
                "תוצאה",
                "דוגמה",
                "סיכום"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"The class is free — this means anyone can join.\" — מה המשמעות של \"this means\" כאן?",
              "options": [
                "למרות זאת",
                "כלומר / זאת אומרת",
                "לדוגמה",
                "לסיכום"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"For example, a student who volunteers learns teamwork.\" — מה המשמעות של \"for example\" כאן?",
              "options": [
                "לסיכום",
                "אולם",
                "לדוגמה",
                "ראשית"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"The evidence is strong; therefore, the plan should go ahead.\" — מה המשמעות של \"therefore\" כאן?",
              "options": [
                "למרות זאת",
                "לדוגמה",
                "מכיוון ש־",
                "לכן / לפיכך"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"Another reason is that it looks good on a CV.\" — מה המשמעות של \"another reason\" כאן?",
              "options": [
                "סיבה נוספת",
                "אותה סיבה",
                "ללא סיבה",
                "הסיבה היחידה"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
