// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c23Lessons: LessonNode[] = [
  {
    "id": "s23-l1",
    "section": "c-23",
    "titleHe": "מילים: בנק דוגמאות למבחן",
    "code": "c.23.1",
    "required": [
      "s22-l1"
    ],
    "position": {
      "x": 70,
      "y": 3360
    },
    "big": false,
    "content": {
      "rounds": [
        {
          "screens": [
            {
              "type": "preface",
              "text": "חמישה משפטי פתיחה שמתאימים כמעט לכל נושא בחיבור."
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"Many students...\"?",
              "options": [
                "\"תלמידים רבים...\"",
                "\"תלמיד אחד...\"",
                "\"אף תלמיד לא...\"",
                "\"המורים...\""
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"For example, a teenager who...\"?",
              "options": [
                "\"לסיכום...\"",
                "\"לדוגמה, מתבגר ש...\"",
                "\"אולם...\"",
                "\"ראשית...\""
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"Studies show...\"?",
              "options": [
                "\"אני מרגיש ש...\"",
                "\"ייתכן ש...\"",
                "\"מחקרים מראים...\"",
                "\"כולם יודעים ש...\""
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"In many schools...\"?",
              "options": [
                "\"בבית ספר אחד...\"",
                "\"בשום בית ספר...\"",
                "\"בבית...\"",
                "\"בבתי ספר רבים...\""
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"According to many experts...\"?",
              "options": [
                "\"לדעת מומחים רבים...\"",
                "\"לדעתי...\"",
                "\"בניגוד למומחים...\"",
                "\"אף מומחה לא...\""
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "______ benefit from doing volunteer work.",
              "options": [
                "Many students...",
                "For example, a teenager who...",
                "Studies show...",
                "In many schools..."
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "______ works part-time learns to manage time.",
              "options": [
                "Studies show...",
                "For example, a teenager who...",
                "In many schools...",
                "According to many experts..."
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "______ that experience helps students later in life.",
              "options": [
                "In many schools...",
                "According to many experts...",
                "Studies show...",
                "Many students..."
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "______, pupils do volunteer work once a week.",
              "options": [
                "According to many experts...",
                "Many students...",
                "For example, a teenager who...",
                "In many schools..."
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "______, real-life experience is very valuable.",
              "options": [
                "According to many experts...",
                "Many students...",
                "For example, a teenager who...",
                "Studies show..."
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"Many students find that a part-time job builds confidence.\" — מה המשמעות של \"Many students...\" כאן?",
              "options": [
                "\"תלמידים רבים...\"",
                "\"תלמיד אחד...\"",
                "\"אף תלמיד לא...\"",
                "\"המורים...\""
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"For example, a teenager who volunteers meets new people.\" — מה המשמעות של \"For example, a teenager who...\" כאן?",
              "options": [
                "\"לסיכום...\"",
                "\"לדוגמה, מתבגר ש...\"",
                "\"אולם...\"",
                "\"ראשית...\""
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"Studies show that reading every day improves writing.\" — מה המשמעות של \"Studies show...\" כאן?",
              "options": [
                "\"אני מרגיש ש...\"",
                "\"ייתכן ש...\"",
                "\"מחקרים מראים...\"",
                "\"כולם יודעים ש...\""
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"In many schools, students join work-experience programmes.\" — מה המשמעות של \"In many schools...\" כאן?",
              "options": [
                "\"בבית ספר אחד...\"",
                "\"בשום בית ספר...\"",
                "\"בבית...\"",
                "\"בבתי ספר רבים...\""
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"According to many experts, teenagers learn best by doing.\" — מה המשמעות של \"According to many experts...\" כאן?",
              "options": [
                "\"לדעת מומחים רבים...\"",
                "\"לדעתי...\"",
                "\"בניגוד למומחים...\"",
                "\"אף מומחה לא...\""
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
