// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c24Lessons: LessonNode[] = [
  {
    "id": "s24-l1",
    "section": "c-24",
    "titleHe": "מילים: סימולציה מלאה",
    "code": "c.24.1",
    "required": [
      "s23-l1"
    ],
    "position": {
      "x": 0,
      "y": 3480
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "הוראות המבחן שחוזרות בכל סימולציה — לזהות ולפעול בלי היסוס."
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"according to\"?",
              "options": [
                "לפי / על פי",
                "בניגוד ל־",
                "למרות",
                "לפני"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"complete the sentence\"?",
              "options": [
                "כתבו משפט חדש",
                "השלימו את המשפט",
                "תקנו שגיאה",
                "קצרו את המשפט"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"what do we learn\"?",
              "options": [
                "מה דעתכם",
                "מה הכותרת",
                "מה אנחנו לומדים",
                "כמה מילים"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"put a √\"?",
              "options": [
                "מחקו",
                "כתבו מחדש",
                "השאירו ריק",
                "סמנו √"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"not true\"?",
              "options": [
                "לא נכון",
                "נכון",
                "חשוב",
                "כתוב בטקסט"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "______ paragraph II, the effect lasts for months.",
              "options": [
                "according to",
                "complete the sentence",
                "what do we learn",
                "put a √"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "______: \"They could not ___.\"",
              "options": [
                "what do we learn",
                "complete the sentence",
                "put a √",
                "not true"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"______ from paragraph I about the study?\"",
              "options": [
                "put a √",
                "not true",
                "what do we learn",
                "according to"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "______ by the TWO correct answers.",
              "options": [
                "not true",
                "according to",
                "complete the sentence",
                "put a √"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "Which statement is ______ according to the text?",
              "options": [
                "not true",
                "according to",
                "complete the sentence",
                "what do we learn"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"According to the writer, kindness helps the giver.\" — מה המשמעות של \"according to\" כאן?",
              "options": [
                "לפי / על פי",
                "בניגוד ל־",
                "למרות",
                "לפני"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"Complete the sentence with words from paragraph I.\" — מה המשמעות של \"complete the sentence\" כאן?",
              "options": [
                "כתבו משפט חדש",
                "השלימו את המשפט",
                "תקנו שגיאה",
                "קצרו את המשפט"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"The question 'what do we learn' asks for the main point.\" — מה המשמעות של \"what do we learn\" כאן?",
              "options": [
                "מה דעתכם",
                "מה הכותרת",
                "מה אנחנו לומדים",
                "כמה מילים"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"Put a √ next to each statement that the text supports.\" — מה המשמעות של \"put a √\" כאן?",
              "options": [
                "מחקו",
                "כתבו מחדש",
                "השאירו ריק",
                "סמנו √"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"Three options are correct; one is not true.\" — מה המשמעות של \"not true\" כאן?",
              "options": [
                "לא נכון",
                "נכון",
                "חשוב",
                "כתוב בטקסט"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
