// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c25Lessons: LessonNode[] = [
  {
    "id": "s25-l1",
    "section": "c-25",
    "titleHe": "מילים: ניתוח שגיאות מסכם",
    "code": "c.25.1",
    "required": [
      "s24-l1"
    ],
    "position": {
      "x": -70,
      "y": 3600
    },
    "big": false,
    "content": {
      "rounds": [
        {
          "screens": [
            {
              "type": "preface",
              "text": "מילים לשיחה על טעויות ולמידה מהן — הסיכום של הקורס."
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"error\"?",
              "options": [
                "שגיאה / טעות",
                "הצלחה",
                "שאלה",
                "כלל"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"pattern\"?",
              "options": [
                "מקרה",
                "דפוס / תבנית",
                "ניחוש",
                "סיכום"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"confident\"?",
              "options": [
                "מבולבל",
                "מודאג",
                "בטוח בעצמי",
                "אדיש"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"ready\"?",
              "options": [
                "עייף",
                "מבולבל",
                "מאחר",
                "מוכן"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"improve\"?",
              "options": [
                "להשתפר / לשפר",
                "להחמיר",
                "לוותר",
                "לשכוח"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "I made one ______ in question 3.",
              "options": [
                "error",
                "pattern",
                "confident",
                "ready"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "Which ______ did I forget to use?",
              "options": [
                "confident",
                "pattern",
                "ready",
                "improve"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "After practice, I feel ______ about P3.",
              "options": [
                "ready",
                "improve",
                "confident",
                "error"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "I feel ______ for the real exam now.",
              "options": [
                "improve",
                "error",
                "pattern",
                "ready"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "Fixing one pattern helped me ______.",
              "options": [
                "improve",
                "error",
                "pattern",
                "confident"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"An error is a signal that shows what to fix.\" — מה המשמעות של \"error\" כאן?",
              "options": [
                "שגיאה / טעות",
                "הצלחה",
                "שאלה",
                "כלל"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"Every wrong answer had a missing pattern.\" — מה המשמעות של \"pattern\" כאן?",
              "options": [
                "מקרה",
                "דפוס / תבנית",
                "ניחוש",
                "סיכום"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"She felt confident before the exam.\" — מה המשמעות של \"confident\" כאן?",
              "options": [
                "מבולבל",
                "מודאג",
                "בטוח בעצמי",
                "אדיש"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"After the simulation, the class was ready.\" — מה המשמעות של \"ready\" כאן?",
              "options": [
                "עייף",
                "מבולבל",
                "מאחר",
                "מוכן"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"I improved a lot by checking my errors.\" — מה המשמעות של \"improve\" כאן?",
              "options": [
                "להשתפר / לשפר",
                "להחמיר",
                "לוותר",
                "לשכוח"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
