// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c3Lessons: LessonNode[] = [
  {
    "id": "s3-l1",
    "section": "c-3",
    "titleHe": "מילים: מגנטים לעין — מספרים ושמות",
    "code": "c.3.1",
    "required": [
      "s2-l1"
    ],
    "position": {
      "x": 70,
      "y": 480
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "מילים שחוזרות בטקסטים על מחקרים וסקרים — במיוחד סביב מספרים ושמות."
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"result(s)\"?",
              "options": [
                "תוצאה / תוצאות",
                "שאלה",
                "סיבה",
                "כותרת"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"found (past of find)\"?",
              "options": [
                "איבד",
                "מצא / גילה",
                "בנה",
                "שכח"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"volunteer(s)\"?",
              "options": [
                "עובד בשכר",
                "מנהל",
                "מתנדב / מתנדבים",
                "לקוח"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"residents\"?",
              "options": [
                "תיירים",
                "עובדים",
                "אורחים",
                "תושבים"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"stress\"?",
              "options": [
                "לחץ / מתח",
                "מנוחה",
                "שמחה",
                "שקט"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "The study's ______ showed a clear drop in noise.",
              "options": [
                "result(s)",
                "found (past of find)",
                "volunteer(s)",
                "residents"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "Scientists ______ that short workouts also help.",
              "options": [
                "volunteer(s)",
                "found (past of find)",
                "residents",
                "stress"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "About 300 ______ took part in the project.",
              "options": [
                "residents",
                "stress",
                "volunteer(s)",
                "result(s)"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "Most ______ of the village said they felt safer.",
              "options": [
                "stress",
                "result(s)",
                "found (past of find)",
                "residents"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "Regular exercise can lower ______ levels.",
              "options": [
                "stress",
                "result(s)",
                "found (past of find)",
                "volunteer(s)"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"The results showed that most residents were happier.\" — מה המשמעות של \"result(s)\" כאן?",
              "options": [
                "תוצאה / תוצאות",
                "שאלה",
                "סיבה",
                "כותרת"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"The researchers found that the effect lasted for months.\" — מה המשמעות של \"found (past of find)\" כאן?",
              "options": [
                "איבד",
                "מצא / גילה",
                "בנה",
                "שכח"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"The volunteers worked for free every weekend.\" — מה המשמעות של \"volunteer(s)\" כאן?",
              "options": [
                "עובד בשכר",
                "מנהל",
                "מתנדב / מתנדבים",
                "לקוח"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"The residents complained about the noise at night.\" — מה המשמעות של \"residents\" כאן?",
              "options": [
                "תיירים",
                "עובדים",
                "אורחים",
                "תושבים"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"Stress levels fell by almost 40 percent.\" — מה המשמעות של \"stress\" כאן?",
              "options": [
                "לחץ / מתח",
                "מנוחה",
                "שמחה",
                "שקט"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  },
  {
    "id": "s3-l2",
    "section": "c-3",
    "titleHe": "מציאה וסימון — מספרים ושמות",
    "code": "c.3.2",
    "required": [
      "s3-l1"
    ],
    "position": {
      "x": 0,
      "y": 600
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "בסריקה מהירה, שני סוגי פרטים כמעט תמיד מובילים אל התשובה: מספרים ושמות.\n\nמספר = המספר יחד עם מה שהוא סופר: \"2,000 trees\", \"three hours a week\", \"40%\", \"five years\".\nשם = אנשים, מקומות וארגונים: \"Dr. Maria Santos\", \"Greenville\", \"Greenville University\"."
        },
        {
          "type": "summary",
          "title": "מה מסמנים",
          "lines": [
            "מספרים: המספר + שם העצם שצמוד אליו. לדוגמה: 2,000 trees · three hours · 85% · ten years",
            "שמות: אות גדולה באמצע משפט — אדם, מקום או מוסד. לדוגמה: Dr. Maria Santos · Greenville University · Professor James Wu"
          ]
        },
        {
          "type": "preface",
          "text": "לפניכם הטקסט THE CITY GARDEN PROJECT בשלוש פסקאות. בכל פסקה סמנו את כל המספרים והשמות."
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mark-all",
              "instruction": "פסקה I — סמנו את כל המספרים והשמות",
              "dir": "ltr",
              "text": "Five years ago, the streets of Greenville had almost no plants or trees. The air was polluted, and most residents felt that the city was an unpleasant place to live. A local charity decided to change this. They planted over 2,000 trees and created 15 community gardens across the city. Today, Greenville looks very different.",
              "correctIndices": [
                0,
                1,
                6,
                40,
                41,
                44,
                45,
                46,
                51
              ]
            },
            {
              "type": "mark-all",
              "instruction": "פסקה II — סמנו את כל המספרים והשמות",
              "dir": "ltr",
              "text": "The person behind this change is Dr. Maria Santos, a professor at Greenville University. \"We wanted to show that any city can become greener in less than ten years,\" she explains. Her team worked with more than 300 volunteers from the local community. The volunteers spent an average of three hours a week working in the gardens.",
              "correctIndices": [
                6,
                7,
                8,
                12,
                13,
                27,
                28,
                37,
                38,
                49,
                50
              ]
            },
            {
              "type": "mark-all",
              "instruction": "פסקה III — סמנו את כל המספרים והשמות",
              "dir": "ltr",
              "text": "The results were surprising. According to the charity, 85% of Greenville residents now say the city is a better place to live. Dr. Santos's colleague, Professor James Wu, found that stress levels among residents had fallen by 40%. \"When people have access to green spaces, they feel calmer and happier,\" he says. The project now receives visits from city planners from over 50 countries who want to learn from Greenville's success.",
              "correctIndices": [
                8,
                10,
                22,
                23,
                25,
                26,
                27,
                37,
                62,
                63,
                69
              ]
            }
          ]
        }
      ]
    }
  },
  {
    "id": "s3-l3",
    "section": "c-3",
    "titleHe": "שימוש במספרים ושמות לניווט",
    "code": "c.3.3",
    "required": [
      "s3-l2"
    ],
    "position": {
      "x": -70,
      "y": 720
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "עד עכשיו סימנתם מספרים ושמות. עכשיו משתמשים בהם כדי לנווט מהר אל התשובה — בלי לקרוא את כל הטקסט."
        },
        {
          "type": "summary",
          "title": "P2 · מספרים   |   P3 · שמות",
          "lines": [
            "P2 (מספר בשאלה): חפשו את המספר בטקסט ← ודאו שהוא צמוד לדבר הנכון ← זו התשובה",
            "P3 (שם בשאלה): לכו לפסקה של אותו שם ← קראו רק שם ← אל תקראו פסקאות אחרות"
          ]
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "timed-passage",
              "label": "THE CITY GARDEN PROJECT",
              "timerKey": "s3garden",
              "text": "Five years ago, the streets of Greenville had almost no plants or trees. The air was polluted, and most residents felt that the city was an unpleasant place to live. A local charity decided to change this. They planted over 2,000 trees and created 15 community gardens across the city. Today, Greenville looks very different.\n\nThe person behind this change is Dr. Maria Santos, a professor at Greenville University. \"We wanted to show that any city can become greener in less than ten years,\" she explains. Her team worked with more than 300 volunteers from the local community. The volunteers spent an average of three hours a week working in the gardens.\n\nThe results were surprising. According to the charity, 85% of Greenville residents now say the city is a better place to live. Dr. Santos's colleague, Professor James Wu, found that stress levels among residents had fallen by 40%. \"When people have access to green spaces, they feel calmer and happier,\" he says. The project now receives visits from city planners from over 50 countries who want to learn from Greenville's success.",
              "questions": [
                {
                  "prompt": "How many trees did the charity plant in Greenville? (paragraph I)",
                  "options": [
                    "Over 2,000",
                    "About 200",
                    "15",
                    "More than 300"
                  ],
                  "correctIndex": 0
                },
                {
                  "prompt": "According to Dr. Maria Santos, what did her team want to show? (paragraph II)",
                  "options": [
                    "That any city can become greener in less than ten years",
                    "That Greenville was polluted five years ago",
                    "That 300 volunteers were not enough",
                    "That stress levels fell by 40%"
                  ],
                  "correctIndex": 0
                },
                {
                  "prompt": "How many hours a week did the volunteers spend in the gardens? (paragraph II)",
                  "options": [
                    "An average of three hours",
                    "Ten years",
                    "Over 50 hours",
                    "85 hours"
                  ],
                  "correctIndex": 0
                },
                {
                  "prompt": "What do we learn from Professor James Wu about the results? (paragraph III)",
                  "options": [
                    "Why he decided to study the Greenville project",
                    "How stress levels changed among residents",
                    "How many people visited Greenville from other countries",
                    "Why he disagrees with Dr. Santos's findings"
                  ],
                  "correctIndex": 1
                }
              ]
            },
            {
              "type": "preface",
              "text": "אתגר מתוזמן: טקסט חדש, שתי שאלות. השתמשו ב-P2 וב-P3."
            },
            {
              "type": "timed-passage",
              "label": "SPORT FOR ALL",
              "timerKey": "s3sport",
              "text": "A new community sports programme in the city of Portland has helped over 4,000 residents become more active over the past two years. The programme offers free fitness classes three times a week in 12 different neighbourhoods. According to Dr. Laura Kim, who runs the programme, the idea is simple. \"We bring the sport to the people, not the people to the sport,\" she says. \"Most people want to be active — they just need the opportunity.\" Professor Marcus Allen of Portland State University found that participants in the programme were 60% less likely to suffer from stress-related health problems.",
              "questions": [
                {
                  "prompt": "According to Professor Marcus Allen, how did the programme affect participants' health?",
                  "options": [
                    "They were 60% less likely to have stress-related health problems",
                    "They exercised for 60 minutes more each day",
                    "They were twice as likely to join a gym",
                    "They became 40% stronger"
                  ],
                  "correctIndex": 0
                },
                {
                  "prompt": "What does Dr. Laura Kim explain about the programme?",
                  "options": [
                    "Why sports equipment is expensive in Portland",
                    "How many people run the programme every year",
                    "Why the programme brings sport to different neighbourhoods",
                    "How participants became healthier than before"
                  ],
                  "correctIndex": 2
                }
              ]
            },
            {
              "type": "time-result",
              "label": "סיימתם את האתגר!",
              "timerKey": "s3sport"
            }
          ]
        }
      ]
    }
  }
];
