// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c3Lessons: LessonNode[] = [
  {
    "id": "eye_catch_intro",
    "section": "c-3",
    "titleHe": "למה מספרים ושמות",
    "code": "c.3.1",
    "required": [
      "s2-l1"
    ],
    "position": {
      "x": 70,
      "y": 480
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": ".**🔑 הכלל האחד שישנה לך את הציון**\nרוב התלמידים קוראים את הטקסט מההתחלה ועד הסוף.\n\nזו טעות.\nהמבחן לא בודק אם קראת — הוא בודק אם **מצאת**.\n\n**זה אומר:**\n\nקרא קודם את **השאלה**.\n\nרק אחרי שאתה יודע מה אתה מחפש — תיגש לטקסט"
        },
        {
          "type": "preface",
          "text": "**🧲 מגנטי עיניים — הטריק שעובד תמיד**\nכשאתה מסתכל על שאלה, שתי קבוצות מילים קופצות לעין **עוד לפני שקראת משהו:**\n\n**מספרים** — *1948, three hours, 12%*\n**שמות** — *David Ben-Gurion, Tel Aviv, NASA*\n\nקוראים להם **מגנטי עיניים** — כי העין שלך נמשכת אליהם אוטומטית.\n\n**אז מה עושים עם זה?**\nמצאת מגנט בשאלה? זו **כתובת**.\n\nעכשיו אתה הולך לטקסט ומחפש **אותו מגנט בדיוק.**\n\nהתשובה כמעט תמיד נמצאת ממש לידו.\n\n**דוגמה:**\n\nהשאלה: *\"What happened after the **1967** war?\"*\n\nהמגנט: **1967**\nעכשיו פשוט תמצא **1967** בטקסט — וקרא רק את המשפט שלידו."
        },
        {
          "type": "summary",
          "title": "שני המגנטים",
          "lines": [
            "**🔢 מספר = הספרה + מה שהיא סופרת**\nרק הספרה לבד היא **לא** מגנט שלם.\nהעין שלך — ועיני הבוחנים — מחפשות את **היחידה המלאה:**\n\nהספרה+ מה שהיא סופרתהמגנט השלם 2,000 trees**2,000 trees **three hours a week **three hours a week **40% **40% **five years **five years**\n\n**למה זה חשוב?**\nכשתחפש בטקסט — אתה מחפש את **שתי המילים ביחד**, לא רק את הספרה.\n\nככה תדע שמצאת את המקום הנכון",
            "**🔠 שם = אדם, מקום, או ארגון**\nאיך מזהים שם בטקסט אנגלי?\n**אות גדולה באמצע משפט — זה תמיד שם.**\n\nסוגדוגמאותאדם**Dr. Maria Santos · John Miller**מקום**Greenville · Lake Ontario**ארגון**Greenville University · NASA**\n\n**למה האות הגדולה כל כך שימושית?**\nבעברית קשה לזהות שמות — כולם נראים אותו דבר.\n\nבאנגלית? השם **קופץ** מהשורה. העין שלך תופסת אותו אוטומטית, גם בלי לקרוא.\n\n**נסה:**\n\n*\"What did Dr. Maria Santos discover in Greenville?\"*\n\nכמה מגנטים יש כאן — ומה הם?"
          ]
        },
        {
          "type": "steps",
          "steps": [
            "למחוק עמוד זה",
            "השאלה: \"How many trees did they plant?\" — אין מספר בשאלה, אבל יש מילה שנחפש: trees.",
            "בטקסט שני מספרים: 2,000 ו-15. בודקים מה צמוד לכל אחד: 2,000 trees · 15 community gardens.",
            "המספר שצמוד ל-trees הוא 2,000. זו התשובה. לא מספיק למצוא מספר — צריך את המספר שצמוד לדבר הנכון."
          ]
        },
        {
          "type": "passage-mcq",
          "text": "Every year, students help clean parks, visit elderly people, and collect food for families in need. Last year, a student named Daniel suggested collecting books for children too. More than 300 books were collected in two weeks and given to local schools.",
          "questions": [
            {
              "prompt": "What did Daniel suggest collecting?",
              "options": [
                "Books for children",
                "Food for families",
                "Clothes for the elderly"
              ],
              "correctIndex": 0
            }
          ]
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "בשאלה כתוב: \"How many hours a week did the volunteers work?\" מה עושים קודם?",
              "options": [
                "מחפשים בטקסט את המספרים, ואז בוחרים את זה שצמוד למילה hours",
                "קוראים את הטקסט מההתחלה עד הסוף",
                "מתרגמים כל מילה בשאלה",
                "מנחשים לפי ההיגיון"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "בשאלה מופיע השם \"Professor James Wu\". מה זה אומר לנו?",
              "options": [
                "שצריך לדעת מי הוא",
                "שהתשובה נמצאת בפסקה שבה מופיע השם",
                "שהשאלה קשה במיוחד",
                "שאין תשובה בטקסט"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"The programme offers free classes three times a week in 12 neighbourhoods.\"\nבכמה שכונות?",
              "options": [
                "three",
                "a week",
                "12",
                "לא כתוב"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "למה \"12\" לבד היא לא תשובה מלאה?",
              "options": [
                "כי צריך לכתוב את המספר במילים",
                "כי 12 מספר קטן מדי",
                "כי המספר בטקסט תמיד שגוי",
                "כי מספר בלי מה שהוא סופר לא אומר כלום — צריך 12 neighbourhoods"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה נחשב \"שם\" בטקסט באנגלית?",
              "options": [
                "אדם, מקום או ארגון — מילה או כמה מילים שמתחילות באות גדולה (Dr. Maria Santos, Greenville)",
                "כל מילה ארוכה",
                "המילה הראשונה בפסקה",
                "כל מילה במרכאות"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  },
  {
    "id": "s3-l1",
    "section": "c-3",
    "titleHe": "מילים: מגנטים לעין — מספרים ושמות",
    "code": "c.3.2",
    "required": [
      "eye_catch_intro"
    ],
    "position": {
      "x": 100,
      "y": 570
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "word-card",
          "word": "result",
          "translationHe": "תוצאה"
        },
        {
          "type": "word-card",
          "word": "found (past of find)",
          "translationHe": "מצא / גילה"
        },
        {
          "type": "word-card",
          "word": "volunteer(s)",
          "translationHe": "מתנדב / מתנדבים"
        },
        {
          "type": "word-card",
          "word": "residents",
          "translationHe": "תושבים"
        },
        {
          "type": "word-card",
          "word": "stress",
          "translationHe": "לחץ / מתח"
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"result\"?",
              "options": [
                "תוצאה",
                "שאלה",
                "סיבה",
                "כותרת"
              ],
              "correctIndex": 0
            },
            {
              "type": "spell-word",
              "word": "result",
              "mode": "copy"
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"found (past of find)\"?",
              "options": [
                "איבד",
                "מצא / גילה",
                "בנה",
                "שכח"
              ],
              "correctIndex": 1
            },
            {
              "type": "spell-word",
              "word": "found",
              "mode": "copy"
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"volunteer(s)\"?",
              "options": [
                "עובד בשכר",
                "מנהל",
                "מתנדב / מתנדבים",
                "לקוח"
              ],
              "correctIndex": 2
            },
            {
              "type": "spell-word",
              "word": "volunteers",
              "mode": "copy"
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"residents\"?",
              "options": [
                "תיירים",
                "עובדים",
                "אורחים",
                "תושבים"
              ],
              "correctIndex": 3
            },
            {
              "type": "spell-word",
              "word": "residents",
              "mode": "copy"
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"stress\"?",
              "options": [
                "לחץ / מתח",
                "מנוחה",
                "שמחה",
                "שקט"
              ],
              "correctIndex": 0
            },
            {
              "type": "spell-word",
              "word": "stress",
              "mode": "copy"
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "The study's ______ showed a clear drop in noise.",
              "options": [
                "results",
                "found",
                "volunteers",
                "residents"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "Scientists ______ that short workouts also help.",
              "options": [
                "volunteer",
                "found (past of find)",
                "residents",
                "stress"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "About 300 ______ took part in the project.",
              "options": [
                "residents",
                "stress",
                "volunteer(s)",
                "result(s)"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "Most ______ of the village said they felt safer.",
              "options": [
                "stress",
                "result(s)",
                "found (past of find)",
                "residents"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "Regular exercise can lower ______ levels.",
              "options": [
                "stress",
                "result(s)",
                "found (past of find)",
                "volunteer(s)"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"The results showed that most residents were happier.\" — מה המשמעות של \"result(s)\" כאן?",
              "options": [
                "תוצאה / תוצאות",
                "שאלה",
                "סיבה",
                "כותרת"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"The researchers found that the effect lasted for months.\" — מה המשמעות של \"found (past of find)\" כאן?",
              "options": [
                "איבד",
                "מצא / גילה",
                "בנה",
                "שכח"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"The volunteers worked for free every weekend.\" — מה המשמעות של \"volunteer(s)\" כאן?",
              "options": [
                "עובד בשכר",
                "מנהל",
                "מתנדב / מתנדבים",
                "לקוח"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"The residents complained about the noise at night.\" — מה המשמעות של \"residents\" כאן?",
              "options": [
                "תיירים",
                "עובדים",
                "אורחים",
                "תושבים"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"Stress levels fell by almost 40 percent.\" — מה המשמעות של \"stress\" כאן?",
              "options": [
                "לחץ / מתח",
                "מנוחה",
                "שמחה",
                "שקט"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  },
  {
    "id": "s3-l2",
    "section": "c-3",
    "titleHe": "מציאה וסימון — מספרים ושמות",
    "code": "c.3.3",
    "required": [
      "s3-l1"
    ],
    "position": {
      "x": 70,
      "y": 660
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "**🎯 עכשיו מתאמנים**\nלמדנו שני סוגי מגנטים:\n\n**מספרים** — הספרה + מה שהיא סופרת\n**שמות** — אדם, מקום, ארגון — תמיד באות גדולה\n\n**המשימה שלך עכשיו — רק לסמן, לא לענות.**\nלא צריך להבין את השאלה.\n\nלא צריך למצוא תשובה.\n\nרק לעצור על כל מגנט שאתה רואה.\n\n**נתחיל בקל — עברית:**\n\n*\"כמה עצים נטע יוסי כהן בפארק הלאומי בתוך שלוש שנים?\"*\n\nכמה מגנטים מצאת?\n\n**עכשיו אנגלית:**\n\n*\"How many students did Dr. Lisa Park teach at Riverside College in 2019?\"*\n\nכמה מגנטים מצאת עכשיו?"
        },
        {
          "type": "summary",
          "title": "מה מסמנים",
          "lines": [
            "מספר: המספר + שם העצם שצמוד אליו — 45 תלמידים · 2,000 trees · 85%",
            "שם: אדם, מקום או ארגון — מיכל ברק · Greenville University · Dr. Maria Santos"
          ]
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mark-all",
              "instruction": "סמנו את כל המספרים — יחד עם מה שהם סופרים",
              "dir": "rtl",
              "text": "לפני שלוש שנים נפתח בבית הספר מועדון מדע. נרשמו אליו 45 תלמידים, והם נפגשים פעמיים בשבוע.",
              "correctIndices": [
                1,
                2,
                10,
                11,
                14,
                15
              ],
              "wordBank": []
            },
            {
              "type": "mark-all",
              "instruction": "סמנו את כל השמות — אנשים, מקומות וארגונים",
              "dir": "rtl",
              "text": "ד״ר נועה לוי מאוניברסיטת חיפה ביקרה בבית הספר, ויחד עם עיריית חיפה פתחה מעבדה חדשה.",
              "correctIndices": [
                0,
                1,
                2,
                3,
                4,
                10,
                11
              ]
            }
          ]
        },
        {
          "screens": [
            {
              "type": "preface",
              "text": "עכשיו יחד: גם מספרים וגם שמות, באותו טקסט."
            },
            {
              "type": "mark-all",
              "instruction": "סמנו את כל המספרים והשמות",
              "dir": "rtl",
              "text": "בשנת 2019 פתחה עיריית תל אביב 12 גינות קהילתיות. המנהלת, שרה כהן, מספרת שכ-800 מתנדבים עבדו שם שעתיים בשבוע.",
              "correctIndices": [
                0,
                1,
                3,
                4,
                5,
                6,
                7,
                10,
                11,
                13,
                14,
                17,
                18
              ]
            }
          ]
        },
        {
          "screens": [
            {
              "type": "preface",
              "text": "אותו דבר בדיוק, באנגלית. אל תתרגמו — רק סרקו בעיניים."
            },
            {
              "type": "mark-all",
              "instruction": "פסקה I — סמנו את כל המספרים בלבד",
              "dir": "ltr",
              "text": "Five years ago, the streets of Greenville had almost no plants or trees. The air was polluted, and most residents felt that the city was an unpleasant place to live. A local charity decided to change this. They planted over 2,000 trees and created 15 community gardens across the city. Today, Greenville looks very different.",
              "correctIndices": [
                0,
                1,
                40,
                41,
                44,
                45,
                46
              ]
            },
            {
              "type": "mark-all",
              "instruction": "פסקה II — סמנו את כל השמות בלבד",
              "dir": "ltr",
              "text": "The person behind this change is Dr. Maria Santos, a professor at Greenville University. \"We wanted to show that any city can become greener in less than ten years,\" she explains. Her team worked with more than 300 volunteers from the local community. The volunteers spent an average of three hours a week working in the gardens.",
              "correctIndices": [
                6,
                7,
                8,
                12,
                13
              ]
            }
          ]
        },
        {
          "screens": [
            {
              "type": "preface",
              "text": "השלב האחרון: מספרים ושמות יחד, באנגלית."
            },
            {
              "type": "mark-all",
              "instruction": "סמנו את כל המספרים והשמות",
              "dir": "ltr",
              "text": "A new community sports programme in the city of Portland has helped over 4,000 residents become more active over the past two years. The programme offers free fitness classes three times a week in 12 different neighbourhoods.",
              "correctIndices": [
                9,
                13,
                14,
                21,
                22,
                29,
                30,
                34,
                35,
                36
              ]
            },
            {
              "type": "mark-all",
              "instruction": "פסקה III — סמנו את כל המספרים והשמות",
              "dir": "ltr",
              "text": "The results were surprising. According to the charity, 85% of Greenville residents now say the city is a better place to live. Dr. Santos's colleague, Professor James Wu, found that stress levels among residents had fallen by 40%. \"When people have access to green spaces, they feel calmer and happier,\" he says. The project now receives visits from city planners from over 50 countries who want to learn from Greenville's success.",
              "correctIndices": [
                8,
                10,
                22,
                23,
                25,
                26,
                27,
                37,
                62,
                63,
                69
              ]
            }
          ]
        }
      ]
    }
  },
  {
    "id": "s3-l3",
    "section": "c-3",
    "titleHe": "שימוש במספרים ושמות לניווט",
    "code": "c.3.4",
    "required": [
      "s3-l2"
    ],
    "position": {
      "x": 0,
      "y": 750
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "סימנתם. עכשיו משתמשים.\n\nמכאן יש טקסט ושאלות, והמטרה היא למצוא פרט אחד קטן בטקסט — מהר, בעזרת המגנט שבשאלה."
        },
        {
          "type": "summary",
          "title": "P2 · מספרים   |   P3 · שמות",
          "lines": [
            "P2 — מספר בשאלה: מחפשים אותו בטקסט ← בודקים שהוא צמוד לדבר הנכון ← זו התשובה",
            "P3 — שם בשאלה: הולכים לפסקה של אותו שם ← קוראים רק שם ← לא נוגעים בשאר"
          ]
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "preface",
              "text": "מתחילים בעברית, כדי שהטכניקה תהיה ברורה לפני שמוסיפים אנגלית."
            },
            {
              "type": "mcq",
              "prompt": "\"בשנה שעברה נפתחה בעיר מודיעין ספרייה חדשה. הספרנית הראשית, מיכל ברק, מספרת ש-1,200 תלמידים נרשמו אליה בחודש הראשון. הספרייה פתוחה חמישה ימים בשבוע, ומתנדבים מבית הספר התיכון עוזרים בה שלוש שעות בשבוע.\"\n\nכמה תלמידים נרשמו בחודש הראשון?",
              "options": [
                "1,200",
                "חמישה",
                "שלוש",
                "לא כתוב בטקסט"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "לפי מיכל ברק, מה אנחנו לומדים?",
              "options": [
                "כמה ימים בשבוע הספרייה פתוחה",
                "כמה תלמידים נרשמו לספרייה בחודש הראשון",
                "כמה עולה מנוי לספרייה",
                "מי בנה את הספרייה"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "כמה שעות בשבוע עוזרים המתנדבים בספרייה?",
              "options": [
                "חמישה ימים",
                "1,200 שעות",
                "שלוש שעות",
                "שעה אחת"
              ],
              "correctIndex": 2
            }
          ]
        },
        {
          "screens": [
            {
              "type": "preface",
              "text": "אותה טכניקה, טקסט באנגלית. קראו קודם את השאלה, מצאו את המגנט, ורק אז גשו לטקסט."
            },
            {
              "type": "timed-passage",
              "label": "THE CITY GARDEN PROJECT",
              "timerKey": "s3garden",
              "text": "Five years ago, the streets of Greenville had almost no plants or trees. The air was polluted, and most residents felt that the city was an unpleasant place to live. A local charity decided to change this. They planted over 2,000 trees and created 15 community gardens across the city. Today, Greenville looks very different.\n\nThe person behind this change is Dr. Maria Santos, a professor at Greenville University. \"We wanted to show that any city can become greener in less than ten years,\" she explains. Her team worked with more than 300 volunteers from the local community. The volunteers spent an average of three hours a week working in the gardens.\n\nThe results were surprising. According to the charity, 85% of Greenville residents now say the city is a better place to live. Dr. Santos's colleague, Professor James Wu, found that stress levels among residents had fallen by 40%. \"When people have access to green spaces, they feel calmer and happier,\" he says. The project now receives visits from city planners from over 50 countries who want to learn from Greenville's success.",
              "questions": [
                {
                  "prompt": "How many trees did the charity plant in Greenville? (paragraph I)",
                  "options": [
                    "Over 2,000",
                    "About 200",
                    "15",
                    "More than 300"
                  ],
                  "correctIndex": 0
                },
                {
                  "prompt": "According to Dr. Maria Santos, what did her team want to show? (paragraph II)",
                  "options": [
                    "That any city can become greener in less than ten years",
                    "That Greenville was polluted five years ago",
                    "That 300 volunteers were not enough",
                    "That stress levels fell by 40%"
                  ],
                  "correctIndex": 0
                },
                {
                  "prompt": "How many hours a week did the volunteers spend in the gardens? (paragraph II)",
                  "options": [
                    "An average of three hours",
                    "Ten years",
                    "Over 50 hours",
                    "85 hours"
                  ],
                  "correctIndex": 0
                },
                {
                  "prompt": "What do we learn from Professor James Wu about the results? (paragraph III)",
                  "options": [
                    "Why he decided to study the Greenville project",
                    "How stress levels changed among residents",
                    "How many people visited Greenville from other countries",
                    "Why he disagrees with Dr. Santos's findings"
                  ],
                  "correctIndex": 1
                }
              ]
            },
            {
              "type": "summary",
              "title": "מה עשינו כאן",
              "lines": [
                "שאלות 1 ו-3: מספר בשאלה ← P2, מחפשים את המספר שצמוד לדבר הנכון",
                "שאלות 2 ו-4: שם בשאלה ← P3, ישר לפסקה שבה מופיע השם"
              ]
            }
          ]
        },
        {
          "screens": [
            {
              "type": "preface",
              "text": "עכשיו על הזמן. טקסט קצר, שתי שאלות. אל תקראו הכל — סרקו."
            },
            {
              "type": "timed-passage",
              "label": "SPORT FOR ALL",
              "timerKey": "s3sport",
              "text": "A new community sports programme in the city of Portland has helped over 4,000 residents become more active over the past two years. The programme offers free fitness classes three times a week in 12 different neighbourhoods. According to Dr. Laura Kim, who runs the programme, the idea is simple. \"We bring the sport to the people, not the people to the sport,\" she says. \"Most people want to be active — they just need the opportunity.\" Professor Marcus Allen of Portland State University found that participants in the programme were 60% less likely to suffer from stress-related health problems.",
              "questions": [
                {
                  "prompt": "According to Professor Marcus Allen, how did the programme affect participants' health?",
                  "options": [
                    "They were 60% less likely to have stress-related health problems",
                    "They exercised for 60 minutes more each day",
                    "They were twice as likely to join a gym",
                    "They became 40% stronger"
                  ],
                  "correctIndex": 0
                },
                {
                  "prompt": "What does Dr. Laura Kim explain about the programme?",
                  "options": [
                    "Why sports equipment is expensive in Portland",
                    "How many people run the programme every year",
                    "Why the programme brings sport to different neighbourhoods",
                    "How participants became healthier than before"
                  ],
                  "correctIndex": 2
                }
              ]
            },
            {
              "type": "time-result",
              "label": "סיימתם את האתגר!",
              "timerKey": "s3sport"
            }
          ]
        }
      ]
    }
  }
];
