// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c4Lessons: LessonNode[] = [
  {
    "id": "s4-l1",
    "section": "c-4",
    "titleHe": "מילות שלילה, הגבלה וניגוד — המילים",
    "code": "c.4.1",
    "required": [
      "s3-l3"
    ],
    "position": {
      "x": -100,
      "y": 840
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "מילים שמסמנות ניגוד או שינוי כיוון בטקסט — ומילות מפתח שכדאי לשים לב אליהן."
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"however\"?",
              "options": [
                "אולם / אבל",
                "לכן",
                "לדוגמה",
                "בנוסף"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"although\"?",
              "options": [
                "מכיוון ש־",
                "למרות ש־",
                "לכן",
                "כלומר"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"benefit(s)\"?",
              "options": [
                "חיסרון",
                "מחיר",
                "יתרון / תועלת",
                "סיכון"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"effective\"?",
              "options": [
                "יקר",
                "איטי",
                "מסוכן",
                "יעיל"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"responsible\"?",
              "options": [
                "אחראי",
                "עצלן",
                "מפוזר",
                "ביישן"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "The apps are popular. ______, not all of them work well.",
              "options": [
                "however",
                "although",
                "benefit(s)",
                "effective"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "______ the class was free, few people came.",
              "options": [
                "benefit(s)",
                "although",
                "effective",
                "responsible"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "One ______ of working is learning responsibility.",
              "options": [
                "effective",
                "responsible",
                "benefit(s)",
                "however"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "Short workouts can be just as ______ as long ones.",
              "options": [
                "responsible",
                "however",
                "although",
                "effective"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "Volunteering makes teenagers more ______.",
              "options": [
                "responsible",
                "however",
                "although",
                "benefit(s)"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"However, experts say it is never too late to learn.\" — מה המשמעות של \"however\" כאן?",
              "options": [
                "אולם / אבל",
                "לכן",
                "לדוגמה",
                "בנוסף"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"Although adults start later, they often improve faster.\" — מה המשמעות של \"although\" כאן?",
              "options": [
                "מכיוון ש־",
                "למרות ש־",
                "לכן",
                "כלומר"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"The benefits of volunteering go beyond a good feeling.\" — מה המשמעות של \"benefit(s)\" כאן?",
              "options": [
                "חיסרון",
                "מחיר",
                "יתרון / תועלת",
                "סיכון"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"The most effective programmes meet twice a week.\" — מה המשמעות של \"effective\" כאן?",
              "options": [
                "יקר",
                "איטי",
                "מסוכן",
                "יעיל"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"Students became more responsible after the programme.\" — מה המשמעות של \"responsible\" כאן?",
              "options": [
                "אחראי",
                "עצלן",
                "מפוזר",
                "ביישן"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  },
  {
    "id": "s4-l2a",
    "section": "c-4",
    "titleHe": "מילות שלילה — זיהוי וסימון",
    "code": "c.4.2a",
    "required": [
      "s4-l1"
    ],
    "position": {
      "x": -100,
      "y": 960
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "! WARNING — P4 changes everything.\nWhen you see NOT, NEVER, NO or NOT ALL in a question, you are NOT looking for what is true.\nYou are hunting for the statement the text says is FALSE — or never says at all.\n\nכשאתם רואים NOT, NEVER, NO, NOT ALL בשאלה — אתם לא מחפשים מה נכון. אתם מחפשים מה לא נכון."
        },
        {
          "type": "summary",
          "title": "מילות השלילה",
          "lines": [
            "not · no · never — שוללות: הופכות את המשפט למשמעות ההפוכה",
            "without — בלי / ללא",
            "cannot — לא יכול",
            "not all — לא כל, רק חלק. שונה לגמרי מ־\"none\""
          ]
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"without\"?",
              "options": [
                "בלי / ללא",
                "עם",
                "בתוך",
                "בגלל"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"never\"?",
              "options": [
                "תמיד",
                "אף פעם לא",
                "לפעמים",
                "בדרך כלל"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"cannot\"?",
              "options": [
                "חייב",
                "רוצה",
                "לא יכול",
                "מנסה"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"not all types produce the same results\" — מה זה אומר?",
              "options": [
                "כל הסוגים זהים",
                "אף סוג לא עובד",
                "כל הסוגים שונים זה מזה",
                "חלק מהסוגים שונים מהאחרים"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"no classroom can replace it\" — מה זה אומר?",
              "options": [
                "שום כיתה לא יכולה להחליף את זה",
                "כל כיתה יכולה להחליף את זה",
                "רק כיתה אחת יכולה",
                "הכיתה טובה יותר"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "preface",
              "text": "עכשיו מוצאים אותן בטקסט. לפניכם פסקה — סמנו כל מילת שלילה. בנק המילים למעלה."
            },
            {
              "type": "mark-all",
              "instruction": "סמנו את כל מילות השלילה",
              "text": "The benefits of volunteering go beyond simple happiness. Dr. Sarah Okafor studied the effects of volunteering on mental health for ten years. She found that teenagers who volunteer feel less stressed and sleep better than those who do not. However, not all types of volunteering produce the same results. According to Okafor, the most effective programmes bring young people face to face with the people they help — not online activities.",
              "correctIndices": [
                38,
                40,
                41,
                68
              ],
              "wordBank": [
                "not",
                "no",
                "never",
                "without",
                "cannot",
                "not all"
              ]
            }
          ]
        },
        {
          "screens": [
            {
              "type": "preface",
              "text": "הטקסט המלא, בלי בנק מילים, עם שעון. סרקו — אל תקראו מילה־מילה."
            },
            {
              "type": "mark-all",
              "instruction": "GIVING TIME, GAINING HAPPINESS — סמנו כל מילת שלילה",
              "text": "GIVING TIME, GAINING HAPPINESS\nI  Every year, millions of young people around the world choose to volunteer — to give their time to help others without payment. A study from a research institute found that young people who volunteer for at least two hours a week are 60% more likely to describe themselves as happy. Researchers were surprised. They had expected that money and success — not helping others — would be the main reason for happiness among teenagers.\nII  The benefits of volunteering go beyond simple happiness. Dr. Sarah Okafor, a researcher at a European university, studied the effects of volunteering on mental health for ten years. She found that teenagers who volunteer feel less stressed and sleep better than those who do not. However, not all types of volunteering produce the same results. According to Okafor, the most effective programmes bring young people face to face with the people they help — not online activities.\nIII  Results from 12 countries show that the benefits of volunteering are not limited to the volunteers themselves. Schools that introduced volunteering programmes found that students became more responsible and more focused in class. Professor David Mills of an Australian university argues that helping others teaches young people skills that no classroom can ever replace. \"When you help someone,\" he says, \"you also help yourself.\"",
              "correctIndices": [
                25,
                66,
                124,
                126,
                127,
                154,
                169,
                207
              ],
              "timerKey": "markNeg"
            },
            {
              "type": "time-result",
              "label": "סיימתם את הסריקה!",
              "timerKey": "markNeg"
            }
          ]
        }
      ]
    }
  },
  {
    "id": "s4-l3a",
    "section": "c-4",
    "titleHe": "שאלת NOT — צוד את המשפט השגוי",
    "code": "c.4.3a",
    "required": [
      "s4-l2a"
    ],
    "position": {
      "x": -100,
      "y": 1080
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "! WARNING — P4 changes everything.\nWhen you see NOT, NEVER, NO or NOT ALL in a question, you are NOT looking for what is true.\nYou are hunting for the statement the text says is FALSE — or never says at all.\n\nכשאתם רואים NOT, NEVER, NO, NOT ALL בשאלה — אתם לא מחפשים מה נכון. אתם מחפשים מה לא נכון."
        },
        {
          "type": "steps",
          "steps": [
            "קראתי את השאלה וראיתי NOT / NEVER / NO / NOT ALL ← עצור.",
            "אני לא מחפש מה נכון — אני צד את המשפט השגוי.",
            "בודק כל אפשרות מול הטקסט: נכון ✓ · נכון ✓ · נכון ✓",
            "זו שנשארה — השגויה — היא התשובה."
          ]
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "שאלה מכילה את המילה NOT. מה אתם מחפשים?",
              "options": [
                "את המשפט שאינו נכון לפי הטקסט",
                "את המשפט הנכון ביותר",
                "את המשפט הארוך ביותר",
                "את המשפט הראשון בפסקה"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "פספסתם את המילה NOT בשאלה. מה יקרה?",
              "options": [
                "לא יקרה כלום, התשובה זהה",
                "תבחרו משפט נכון — והתשובה תיפסל",
                "תקבלו חצי ניקוד",
                "השאלה תתבטל"
              ],
              "correctIndex": 1
            },
            {
              "type": "timed-passage",
              "label": "GIVING TIME, GAINING HAPPINESS",
              "text": "GIVING TIME, GAINING HAPPINESS\nI  Every year, millions of young people around the world choose to volunteer — to give their time to help others without payment. A study from a research institute found that young people who volunteer for at least two hours a week are 60% more likely to describe themselves as happy. Researchers were surprised. They had expected that money and success — not helping others — would be the main reason for happiness among teenagers.\nII  The benefits of volunteering go beyond simple happiness. Dr. Sarah Okafor, a researcher at a European university, studied the effects of volunteering on mental health for ten years. She found that teenagers who volunteer feel less stressed and sleep better than those who do not. However, not all types of volunteering produce the same results. According to Okafor, the most effective programmes bring young people face to face with the people they help — not online activities.\nIII  Results from 12 countries show that the benefits of volunteering are not limited to the volunteers themselves. Schools that introduced volunteering programmes found that students became more responsible and more focused in class. Professor David Mills of an Australian university argues that helping others teaches young people skills that no classroom can ever replace. \"When you help someone,\" he says, \"you also help yourself.\"",
              "timerKey": "s4NotQuiz",
              "questions": [
                {
                  "prompt": "Which statement is NOT true according to paragraph II?",
                  "options": [
                    "All types of volunteering produce the same results.",
                    "Dr. Okafor studied volunteering and mental health for ten years.",
                    "Teenagers who volunteer feel less stressed than those who do not.",
                    "Dr. Okafor found that young volunteers sleep better."
                  ],
                  "correctIndex": 0
                },
                {
                  "prompt": "Which statement is NOT true according to paragraph I?",
                  "options": [
                    "Volunteers give their time without payment.",
                    "Young volunteers are less likely to describe themselves as happy.",
                    "The researchers were surprised by what they found.",
                    "Millions of young people volunteer every year."
                  ],
                  "correctIndex": 1
                },
                {
                  "prompt": "According to paragraph III, which statement is NOT true?",
                  "options": [
                    "Students became more focused in class.",
                    "Professor Mills works at an Australian university.",
                    "The benefits are limited to the volunteers themselves.",
                    "The results come from 12 countries."
                  ],
                  "correctIndex": 2
                },
                {
                  "prompt": "Which statement is NOT mentioned anywhere in the text?",
                  "options": [
                    "Volunteering can improve sleep.",
                    "Some volunteering is done online.",
                    "Schools introduced volunteering programmes.",
                    "Volunteers are paid a small amount for their time."
                  ],
                  "correctIndex": 3
                }
              ]
            },
            {
              "type": "time-result",
              "label": "סיימתם!",
              "timerKey": "s4NotQuiz"
            },
            {
              "type": "summary",
              "title": "P4 — שאלת NOT",
              "lines": [
                "NOT / NEVER / NO / NOT ALL בשאלה ← עצור.",
                "מחפשים את השגוי, לא את הנכון.",
                "בודקים כל אפשרות מול הטקסט — אחת לא תתאים.",
                "מסיחה נפוצה: משפט נכון וברור. הוא הפיתוי, לא התשובה."
              ]
            }
          ]
        }
      ]
    }
  },
  {
    "id": "s4-l2b",
    "section": "c-4",
    "titleHe": "מילות הגבלה — תשובה אחת בלבד",
    "code": "c.4.2b",
    "required": [
      "s4-l1"
    ],
    "position": {
      "x": 0,
      "y": 960
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "P5 — Key limiters: main · most · only · first.\nA limiter narrows the question to ONE answer. Not two, not \"the two best\" — one.\n\nמילת הגבלה בשאלה ← תשובה אחת בלבד."
        },
        {
          "type": "summary",
          "title": "מילות ההגבלה",
          "lines": [
            "main — עיקרי. יש רק אחד.",
            "most — הכי. לא \"אחד מהטובים\" — הטוב ביותר.",
            "only — רק / בלבד.",
            "first — ראשון. לא \"אחד הראשונים\"."
          ]
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"the most effective programmes\" — כמה תשובות מחפשים?",
              "options": [
                "אחת בלבד",
                "שתיים",
                "שלוש",
                "כמה שנמצא"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"main\"?",
              "options": [
                "משני",
                "עיקרי / מרכזי",
                "אחרון",
                "נוסף"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"only\"?",
              "options": [
                "גם",
                "בנוסף",
                "רק / בלבד",
                "לפחות"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"What is the main reason?\" — מה נדרש?",
              "options": [
                "כל הסיבות שבטקסט",
                "שתי סיבות",
                "הסיבה האחרונה",
                "סיבה אחת — העיקרית"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "כתבתם שתי תשובות לשאלה עם \"most\". מה יקרה?",
              "options": [
                "התשובה תיפסל — נדרשה אחת",
                "תקבלו ניקוד על שתיהן",
                "הבודק יבחר את הטובה",
                "לא משנה"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "preface",
              "text": "מוצאים אותן בטקסט. סמנו כל מילת הגבלה. בנק המילים למעלה."
            },
            {
              "type": "mark-all",
              "instruction": "סמנו את כל מילות ההגבלה",
              "text": "THE BOREDOM STUDY\nResearchers at a British university recently published a surprising study about boredom. The study found that people who spent ten minutes doing a boring task before a creative activity produced twice as many creative ideas as those who did not do a boring task first. Dr. Sandi Mann, who led the research, says: \"Boredom allows the brain to wander freely. This is when most creative ideas appear.\" However, she warns that not all types of boredom have the same effect. Only passive boredom — such as watching a blank screen — produced this result. Active boredom, such as a sport or a walk, did not have the same effect.",
              "correctIndices": [
                47,
                66,
                83
              ],
              "wordBank": [
                "main",
                "most",
                "only",
                "first",
                "best"
              ]
            }
          ]
        },
        {
          "screens": [
            {
              "type": "preface",
              "text": "טקסט מלא, בלי בנק מילים, עם שעון. מילות הגבלה נדירות — לכן הן מסגירות את התשובה."
            },
            {
              "type": "mark-all",
              "instruction": "THE EXERCISE MYTH — סמנו כל מילת הגבלה",
              "text": "THE EXERCISE MYTH\nI  Most people believe that to get fit, they need to exercise for at least 30 minutes every day. However, new research suggests this idea may be wrong. According to a study published in the Journal of Sports Science, short bursts of intense exercise — as little as seven minutes a day — can be just as effective as longer workouts. This finding challenges everything most fitness experts have said for decades.\nII  Dr. Jennifer Cho, a sports scientist at Yonsei University in South Korea, tested two groups of volunteers for 12 weeks. The first group exercised for 30 minutes every day. The second group did seven minutes of intense exercise three times a day. At the end, Dr. Cho found that both groups had similar improvements. However, the second group reported feeling more energetic and less stressed.\nIII  Not all scientists agree with these findings. Professor Robert Walsh of Oxford University argues that the research has serious limitations. \"The study only looked at healthy young adults,\" he says. \"We cannot apply these results to older people or those with health problems.\" He also points out that most people cannot maintain these routines for more than a few weeks.",
              "correctIndices": [
                4,
                68,
                97,
                164,
                190
              ],
              "timerKey": "markLim"
            },
            {
              "type": "time-result",
              "label": "סיימתם את הסריקה!",
              "timerKey": "markLim"
            }
          ]
        }
      ]
    }
  },
  {
    "id": "s4-l3b",
    "section": "c-4",
    "titleHe": "שאלה עם מילת הגבלה",
    "code": "c.4.3b",
    "required": [
      "s4-l2b"
    ],
    "position": {
      "x": 0,
      "y": 1080
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "P5 — Key limiters: main · most · only · first.\nA limiter narrows the question to ONE answer. Not two, not \"the two best\" — one.\n\nמילת הגבלה בשאלה ← תשובה אחת בלבד."
        },
        {
          "type": "steps",
          "steps": [
            "ראיתי מילת הגבלה בשאלה — main / most / only / first.",
            "P5: יש תשובה אחת. מפסיק לחפש עוד.",
            "מאתר את אותה מילה בטקסט — היא כמעט תמיד שם.",
            "קורא את המשפט סביבה. זו התשובה."
          ]
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "שאלה כוללת את המילה \"most\". כמה תשובות נכונות יש?",
              "options": [
                "אחת בלבד",
                "שתיים",
                "תלוי בטקסט",
                "כמה שתמצאו"
              ],
              "correctIndex": 0
            },
            {
              "type": "timed-passage",
              "label": "GIVING TIME, GAINING HAPPINESS",
              "text": "GIVING TIME, GAINING HAPPINESS\nI  Every year, millions of young people around the world choose to volunteer — to give their time to help others without payment. A study from a research institute found that young people who volunteer for at least two hours a week are 60% more likely to describe themselves as happy. Researchers were surprised. They had expected that money and success — not helping others — would be the main reason for happiness among teenagers.\nII  The benefits of volunteering go beyond simple happiness. Dr. Sarah Okafor, a researcher at a European university, studied the effects of volunteering on mental health for ten years. She found that teenagers who volunteer feel less stressed and sleep better than those who do not. However, not all types of volunteering produce the same results. According to Okafor, the most effective programmes bring young people face to face with the people they help — not online activities.\nIII  Results from 12 countries show that the benefits of volunteering are not limited to the volunteers themselves. Schools that introduced volunteering programmes found that students became more responsible and more focused in class. Professor David Mills of an Australian university argues that helping others teaches young people skills that no classroom can ever replace. \"When you help someone,\" he says, \"you also help yourself.\"",
              "timerKey": "s4LimQuiz",
              "questions": [
                {
                  "prompt": "According to Dr. Sarah Okafor, what type of volunteering is most effective? (paragraph II)",
                  "options": [
                    "Programmes that bring young people face to face with the people they help",
                    "Online volunteering activities",
                    "Programmes that run for at least ten years",
                    "Any type — they all work equally well"
                  ],
                  "correctIndex": 0
                },
                {
                  "prompt": "According to paragraph I, what did researchers expect to be the main reason for happiness?",
                  "options": [
                    "Helping other people",
                    "Money and success",
                    "Volunteering two hours a week",
                    "Sleeping better at night"
                  ],
                  "correctIndex": 1
                },
                {
                  "prompt": "What is the main idea of paragraph III?",
                  "options": [
                    "Only Australian schools run volunteering programmes",
                    "Classroom teaching is more useful than volunteering",
                    "The benefits of volunteering reach beyond the volunteers themselves",
                    "Volunteering only works in 12 countries"
                  ],
                  "correctIndex": 2
                }
              ]
            },
            {
              "type": "time-result",
              "label": "סיימתם!",
              "timerKey": "s4LimQuiz"
            },
            {
              "type": "summary",
              "title": "P5 — מילת הגבלה",
              "lines": [
                "main · most · only · first ← תשובה אחת.",
                "המילה עצמה כמעט תמיד מופיעה גם בטקסט — חפשו אותה.",
                "שתי תשובות לשאלה עם מילת הגבלה = תשובה פסולה."
              ]
            }
          ]
        }
      ]
    }
  },
  {
    "id": "s4-l2c",
    "section": "c-4",
    "titleHe": "מילות ניגוד — מה בא אחרי",
    "code": "c.4.2c",
    "required": [
      "s4-l1"
    ],
    "position": {
      "x": 100,
      "y": 960
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "P6 — Contrast words: however · but · although.\nThey mark a turn. What comes AFTER them is the new, important information — and it is usually where the answer hides.\n\nמילת ניגוד ← מה שבא אחריה הוא המידע החדש."
        },
        {
          "type": "summary",
          "title": "מילות הניגוד",
          "lines": [
            "however · but — אולם / אבל. המידע החדש בא אחריהן.",
            "although — למרות ש־. הניגוד יושב בתוך משפט אחד.",
            "ראיתם מילת ניגוד? מה שלפניה הוא הרקע. מה שאחריה הוא העיקר."
          ]
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"however\"?",
              "options": [
                "אולם / אבל",
                "לכן",
                "לדוגמה",
                "בנוסף"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"although\"?",
              "options": [
                "מכיוון ש־",
                "למרות ש־",
                "לכן",
                "כלומר"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"The plan is cheap. However, it is very slow.\" — איפה המידע החדש?",
              "options": [
                "לפני However",
                "בשני המשפטים במידה שווה",
                "אחרי However",
                "אין מידע חדש"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"Although it rained, the event went ahead.\" — מה קרה בפועל?",
              "options": [
                "האירוע בוטל",
                "האירוע נדחה בגלל הגשם",
                "לא כתוב",
                "האירוע התקיים"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "ראיתם \"but\" באמצע משפט. איזה חלק חשוב יותר?",
              "options": [
                "מה שבא אחרי but",
                "מה שבא לפני but",
                "שני החלקים שווים",
                "ה-but עצמו"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "preface",
              "text": "מוצאים אותן בטקסט. סמנו כל מילת ניגוד. בנק המילים למעלה."
            },
            {
              "type": "mark-all",
              "instruction": "סמנו את כל מילות הניגוד",
              "text": "THE SLEEP QUESTION\nMost people know that sleep is important for health. However, a new study from the National Sleep Research Centre shows that the quality of sleep matters more than the quantity. Researchers found that people who sleep for six hours of deep, uninterrupted sleep feel more rested than those who sleep for nine hours but wake up several times during the night. Dr. Claire Webb, who led the study, says: \"The most important factor is not the number of hours, but the depth of the sleep.\" She recommends that people avoid screens for at least one hour before going to bed.",
              "correctIndices": [
                12,
                56,
                82
              ],
              "wordBank": [
                "however",
                "but",
                "although",
                "while",
                "yet",
                "despite"
              ]
            }
          ]
        },
        {
          "screens": [
            {
              "type": "preface",
              "text": "טקסט מלא, בלי בנק מילים, עם שעון. מילות ניגוד נדירות — וכל אחת מסמנת פנייה בטקסט."
            },
            {
              "type": "mark-all",
              "instruction": "THE EXERCISE MYTH — סמנו כל מילת ניגוד",
              "text": "THE EXERCISE MYTH\nI  Most people believe that to get fit, they need to exercise for at least 30 minutes every day. However, new research suggests this idea may be wrong. According to a study published in the Journal of Sports Science, short bursts of intense exercise — as little as seven minutes a day — can be just as effective as longer workouts. This finding challenges everything most fitness experts have said for decades.\nII  Dr. Jennifer Cho, a sports scientist at Yonsei University in South Korea, tested two groups of volunteers for 12 weeks. The first group exercised for 30 minutes every day. The second group did seven minutes of intense exercise three times a day. At the end, Dr. Cho found that both groups had similar improvements. However, the second group reported feeling more energetic and less stressed.\nIII  Not all scientists agree with these findings. Professor Robert Walsh of Oxford University argues that the research has serious limitations. \"The study only looked at healthy young adults,\" he says. \"We cannot apply these results to older people or those with health problems.\" He also points out that most people cannot maintain these routines for more than a few weeks.",
              "correctIndices": [
                22,
                130
              ],
              "timerKey": "markCon"
            },
            {
              "type": "time-result",
              "label": "סיימתם את הסריקה!",
              "timerKey": "markCon"
            }
          ]
        }
      ]
    }
  }
];
