// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c5Lessons: LessonNode[] = [
  {
    "id": "s5-l1",
    "section": "c-5",
    "titleHe": "מילים: שיטת הרמזור",
    "code": "c.5.1",
    "required": [
      "s4-l3a",
      "s4-l3b",
      "s4-l2c"
    ],
    "position": {
      "x": 70,
      "y": 1200
    },
    "big": false,
    "content": {
      "rounds": [
        {
          "screens": [
            {
              "type": "preface",
              "text": "מילים שמופיעות סביב מחקרים, סיבה ותוצאה."
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"according to\"?",
              "options": [
                "לפי / על פי",
                "בניגוד ל־",
                "למרות",
                "במקום"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"suggest(s)\"?",
              "options": [
                "מוכיח",
                "מרמז / מציע",
                "מכחיש",
                "שוכח"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"affect / effect\"?",
              "options": [
                "מונע",
                "מסתיר",
                "משפיע / השפעה",
                "מודד"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"focus(ed)\"?",
              "options": [
                "מבולבל",
                "עייף",
                "משועמם",
                "מרוכז / התמקד"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"produce(s)\"?",
              "options": [
                "מייצר / יוצר",
                "הורס",
                "מוכר",
                "קונה"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "______ the survey, 30% of adults cannot swim.",
              "options": [
                "according to",
                "suggest(s)",
                "affect / effect",
                "focus(ed)"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "The data ______ that sleep affects memory.",
              "options": [
                "affect / effect",
                "suggest(s)",
                "focus(ed)",
                "produce(s)"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "Loud noise can ______ how well you sleep.",
              "options": [
                "focus(ed)",
                "produce(s)",
                "affect / effect",
                "according to"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "After the change, students were more ______.",
              "options": [
                "produce(s)",
                "according to",
                "suggest(s)",
                "focus(ed)"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "Not all methods ______ the same results.",
              "options": [
                "produce(s)",
                "according to",
                "suggest(s)",
                "affect / effect"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"According to Dr. Okafor, the results were surprising.\" — מה המשמעות של \"according to\" כאן?",
              "options": [
                "לפי / על פי",
                "בניגוד ל־",
                "למרות",
                "במקום"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"The study suggests a link, but does not prove it.\" — מה המשמעות של \"suggest(s)\" כאן?",
              "options": [
                "מוכיח",
                "מרמז / מציע",
                "מכחיש",
                "שוכח"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"Noise affects sleep, and the effect can be serious.\" — מה המשמעות של \"affect / effect\" כאן?",
              "options": [
                "מונע",
                "מסתיר",
                "משפיע / השפעה",
                "מודד"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"The students stayed focused for the whole lesson.\" — מה המשמעות של \"focus(ed)\" כאן?",
              "options": [
                "מבולבל",
                "עייף",
                "משועמם",
                "מרוכז / התמקד"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"The factory produces thousands of devices a day.\" — מה המשמעות של \"produce(s)\" כאן?",
              "options": [
                "מייצר / יוצר",
                "הורס",
                "מוכר",
                "קונה"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
