// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c6Lessons: LessonNode[] = [
  {
    "id": "s6-l1",
    "section": "c-6",
    "titleHe": "מילים: שאלות פרטים",
    "code": "c.6.1",
    "required": [
      "s5-l1"
    ],
    "position": {
      "x": 100,
      "y": 1320
    },
    "big": false,
    "content": {
      "rounds": [
        {
          "screens": [
            {
              "type": "preface",
              "text": "מילים לשאלות פרטים — סיבה, שיפור והתניה."
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"despite\"?",
              "options": [
                "למרות",
                "בגלל",
                "בזכות",
                "לפי"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"improve\"?",
              "options": [
                "להחמיר",
                "לשפר",
                "לשמור",
                "למחוק"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"cause(s)\"?",
              "options": [
                "מונע",
                "פותר",
                "גורם ל־ / סיבה",
                "מסתיר"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"require(s)\"?",
              "options": [
                "מבטל",
                "מציע",
                "שוכח",
                "דורש / זקוק ל־"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"quality\"?",
              "options": [
                "איכות",
                "כמות",
                "מחיר",
                "מהירות"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "______ the noise, she managed to fall asleep.",
              "options": [
                "despite",
                "improve",
                "cause(s)",
                "require(s)"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "Reading every day can ______ your English.",
              "options": [
                "cause(s)",
                "improve",
                "require(s)",
                "quality"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "Too much noise can ______ stress.",
              "options": [
                "require(s)",
                "quality",
                "cause(s)",
                "despite"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "The task ______ full concentration.",
              "options": [
                "quality",
                "despite",
                "improve",
                "require(s)"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "The ______ of your sleep matters more than the hours.",
              "options": [
                "quality",
                "despite",
                "improve",
                "cause(s)"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"Despite the problems, the programme succeeded.\" — מה המשמעות של \"despite\" כאן?",
              "options": [
                "למרות",
                "בגלל",
                "בזכות",
                "לפי"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"Students improved their results within two months.\" — מה המשמעות של \"improve\" כאן?",
              "options": [
                "להחמיר",
                "לשפר",
                "לשמור",
                "למחוק"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"The main cause of the problem was lack of sleep.\" — מה המשמעות של \"cause(s)\" כאן?",
              "options": [
                "מונע",
                "פותר",
                "גורם ל־ / סיבה",
                "מסתיר"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"The programme requires two hours of training a week.\" — מה המשמעות של \"require(s)\" כאן?",
              "options": [
                "מבטל",
                "מציע",
                "שוכח",
                "דורש / זקוק ל־"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"The quality of the classes was very high.\" — מה המשמעות של \"quality\" כאן?",
              "options": [
                "איכות",
                "כמות",
                "מחיר",
                "מהירות"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
