// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c7Lessons: LessonNode[] = [
  {
    "id": "s7-l1",
    "section": "c-7",
    "titleHe": "מילים: שאלות רב־ברירה",
    "code": "c.7.1",
    "required": [
      "s6-l1"
    ],
    "position": {
      "x": 70,
      "y": 1440
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "מילים לשאלות רב־ברירה — דעה, החלפה והצלחה."
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"argue(s)\"?",
              "options": [
                "טוען",
                "מסכים",
                "שותק",
                "מוכיח"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"replace\"?",
              "options": [
                "להוסיף",
                "להחליף",
                "לשבור",
                "לתקן"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"successful\"?",
              "options": [
                "כושל",
                "יקר",
                "מצליח / מוצלח",
                "קשה"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"introduce(d)\"?",
              "options": [
                "ביטל",
                "הסתיר",
                "המשיך",
                "הכניס / הציג לראשונה"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"entire\"?",
              "options": [
                "כל / שלם",
                "חצי",
                "מעט",
                "אף"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "Professor Nkosi ______ that homework is useful.",
              "options": [
                "argue(s)",
                "replace",
                "successful",
                "introduce(d)"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "No app can ______ a real conversation.",
              "options": [
                "successful",
                "replace",
                "introduce(d)",
                "entire"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "The students became more ______ after the change.",
              "options": [
                "introduce(d)",
                "entire",
                "successful",
                "argue(s)"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "The school ______ a new reading programme this year.",
              "options": [
                "entire",
                "argue(s)",
                "replace",
                "introduce(d)"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "The ______ class took part in the experiment.",
              "options": [
                "entire",
                "argue(s)",
                "replace",
                "successful"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"She argues that schools should teach kindness.\" — מה המשמעות של \"argue(s)\" כאן?",
              "options": [
                "טוען",
                "מסכים",
                "שותק",
                "מוכיח"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"Machines will not replace teachers completely.\" — מה המשמעות של \"replace\" כאן?",
              "options": [
                "להוסיף",
                "להחליף",
                "לשבור",
                "לתקן"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"The project was successful in every school that tried it.\" — מה המשמעות של \"successful\" כאן?",
              "options": [
                "כושל",
                "יקר",
                "מצליח / מוצלח",
                "קשה"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"The government introduced a law to protect forests.\" — מה המשמעות של \"introduce(d)\" כאן?",
              "options": [
                "ביטל",
                "הסתיר",
                "המשיך",
                "הכניס / הציג לראשונה"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"The entire village agreed to ban cars.\" — מה המשמעות של \"entire\" כאן?",
              "options": [
                "כל / שלם",
                "חצי",
                "מעט",
                "אף"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
