// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c8Lessons: LessonNode[] = [
  {
    "id": "s8-l1",
    "section": "c-8",
    "titleHe": "מילים: השלמת משפט",
    "code": "c.8.1",
    "required": [
      "s7-l1"
    ],
    "position": {
      "x": 0,
      "y": 1560
    },
    "big": false,
    "content": {
      "rounds": [
        {
          "screens": [
            {
              "type": "preface",
              "text": "מילים להשלמת משפטים — יצירה, צורך והחלפה."
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"develop(s)\"?",
              "options": [
                "מפתח",
                "הורס",
                "מעתיק",
                "מוכר"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"require(s)\"?",
              "options": [
                "מבטל",
                "דורש",
                "מציע",
                "מסתיר"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"replace\"?",
              "options": [
                "להוסיף",
                "לשבור",
                "להחליף",
                "לשמור"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"introduce(d)\"?",
              "options": [
                "ביטל",
                "סיים",
                "הסתיר",
                "הכניס לראשונה"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"benefit(s)\"?",
              "options": [
                "תועלת / להפיק תועלת",
                "נזק",
                "מחיר",
                "סיכון"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "Companies ______ new technology every year.",
              "options": [
                "develop(s)",
                "require(s)",
                "replace",
                "introduce(d)"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "The programme ______ regular practice.",
              "options": [
                "replace",
                "require(s)",
                "introduce(d)",
                "benefit(s)"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "Nothing can ______ a real teacher.",
              "options": [
                "introduce(d)",
                "benefit(s)",
                "replace",
                "develop(s)"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "The company ______ a shorter working week.",
              "options": [
                "benefit(s)",
                "develop(s)",
                "require(s)",
                "introduce(d)"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "Workers ______ from the new training programme.",
              "options": [
                "benefit(s)",
                "develop(s)",
                "require(s)",
                "replace"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"Volunteering helps young people develop new skills.\" — מה המשמעות של \"develop(s)\" כאן?",
              "options": [
                "מפתח",
                "הורס",
                "מעתיק",
                "מוכר"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"This job requires patience and attention.\" — מה המשמעות של \"require(s)\" כאן?",
              "options": [
                "מבטל",
                "דורש",
                "מציע",
                "מסתיר"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"They replaced the old system with a digital one.\" — מה המשמעות של \"replace\" כאן?",
              "options": [
                "להוסיף",
                "לשבור",
                "להחליף",
                "לשמור"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"The school introduced tablets in every classroom.\" — מה המשמעות של \"introduce(d)\" כאן?",
              "options": [
                "ביטל",
                "סיים",
                "הסתיר",
                "הכניס לראשונה"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"One benefit of the change was less stress.\" — מה המשמעות של \"benefit(s)\" כאן?",
              "options": [
                "תועלת / להפיק תועלת",
                "נזק",
                "מחיר",
                "סיכון"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
