// Generated by scripts/snapshot-content.ts — frozen snapshot, edit freely from here on.
import type { LessonNode } from '../types';

export const c9Lessons: LessonNode[] = [
  {
    "id": "s9-l1",
    "section": "c-9",
    "titleHe": "מילים: שתי תשובות נכונות",
    "code": "c.9.1",
    "required": [
      "s8-l1"
    ],
    "position": {
      "x": -70,
      "y": 1920
    },
    "big": false,
    "content": {
      "preface": [
        {
          "type": "preface",
          "text": "מילים לשאלות \"שתי תשובות נכונות\" — נתינה, הגנה וגדילה."
        }
      ],
      "rounds": [
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"responsible\"?",
              "options": [
                "אחראי",
                "עצלן",
                "מפוזר",
                "תלותי"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"provide(s)\"?",
              "options": [
                "לוקח",
                "מספק / נותן",
                "מוכר",
                "מסתיר"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"community\"?",
              "options": [
                "ממשלה",
                "חברה מסחרית",
                "קהילה",
                "משפחה"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"protect(s)\"?",
              "options": [
                "הורס",
                "מוכר",
                "מסתיר",
                "מגן על"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "מה המשמעות של \"increase(d)\"?",
              "options": [
                "הגדיל / עלה",
                "ירד",
                "נעצר",
                "נעלם"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "The programme makes students more ______.",
              "options": [
                "responsible",
                "provide(s)",
                "community",
                "protect(s)"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "The centre ______ free classes for adults.",
              "options": [
                "community",
                "provide(s)",
                "protect(s)",
                "increase(d)"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "The whole ______ helped to clean the park.",
              "options": [
                "protect(s)",
                "increase(d)",
                "community",
                "responsible"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "New laws ______ the forests from damage.",
              "options": [
                "increase(d)",
                "responsible",
                "provide(s)",
                "protect(s)"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "The number of volunteers ______ every year.",
              "options": [
                "increase(d)",
                "responsible",
                "provide(s)",
                "community"
              ],
              "correctIndex": 0
            }
          ]
        },
        {
          "screens": [
            {
              "type": "mcq",
              "prompt": "\"Each teacher is responsible for one small group.\" — מה המשמעות של \"responsible\" כאן?",
              "options": [
                "אחראי",
                "עצלן",
                "מפוזר",
                "תלותי"
              ],
              "correctIndex": 0
            },
            {
              "type": "mcq",
              "prompt": "\"The programme provides books and computers.\" — מה המשמעות של \"provide(s)\" כאן?",
              "options": [
                "לוקח",
                "מספק / נותן",
                "מוכר",
                "מסתיר"
              ],
              "correctIndex": 1
            },
            {
              "type": "mcq",
              "prompt": "\"The local community raised money for the school.\" — מה המשמעות של \"community\" כאן?",
              "options": [
                "ממשלה",
                "חברה מסחרית",
                "קהילה",
                "משפחה"
              ],
              "correctIndex": 2
            },
            {
              "type": "mcq",
              "prompt": "\"Parents want to protect their children from danger.\" — מה המשמעות של \"protect(s)\" כאן?",
              "options": [
                "הורס",
                "מוכר",
                "מסתיר",
                "מגן על"
              ],
              "correctIndex": 3
            },
            {
              "type": "mcq",
              "prompt": "\"Noise increased after the new road was built.\" — מה המשמעות של \"increase(d)\" כאן?",
              "options": [
                "הגדיל / עלה",
                "ירד",
                "נעצר",
                "נעלם"
              ],
              "correctIndex": 0
            }
          ]
        }
      ]
    }
  }
];
