// Generated by scripts/snapshot-content.ts. Aggregates every section's
// LessonNode[] into one lookup. Add new sections to the imports + list below.
import type { LessonNode } from './types';
import { c1Lessons } from './c/c-1';
import { c2Lessons } from './c/c-2';
import { c3Lessons } from './c/c-3';
import { c4Lessons } from './c/c-4';
import { c5Lessons } from './c/c-5';
import { c6Lessons } from './c/c-6';
import { c7Lessons } from './c/c-7';
import { c8Lessons } from './c/c-8';
import { c9Lessons } from './c/c-9';
import { c10Lessons } from './c/c-10';
import { c11Lessons } from './c/c-11';
import { c12Lessons } from './c/c-12';
import { c13Lessons } from './c/c-13';
import { c14Lessons } from './c/c-14';
import { c15Lessons } from './c/c-15';
import { c16Lessons } from './c/c-16';
import { c17Lessons } from './c/c-17';
import { c18Lessons } from './c/c-18';
import { c19Lessons } from './c/c-19';
import { c20Lessons } from './c/c-20';
import { c21Lessons } from './c/c-21';
import { c22Lessons } from './c/c-22';
import { c23Lessons } from './c/c-23';
import { c24Lessons } from './c/c-24';
import { c25Lessons } from './c/c-25';

export * from './types';
export { sectionMeta } from './sectionMeta';

const all: LessonNode[] = [
	...c1Lessons,
	...c2Lessons,
	...c3Lessons,
	...c4Lessons,
	...c5Lessons,
	...c6Lessons,
	...c7Lessons,
	...c8Lessons,
	...c9Lessons,
	...c10Lessons,
	...c11Lessons,
	...c12Lessons,
	...c13Lessons,
	...c14Lessons,
	...c15Lessons,
	...c16Lessons,
	...c17Lessons,
	...c18Lessons,
	...c19Lessons,
	...c20Lessons,
	...c21Lessons,
	...c22Lessons,
	...c23Lessons,
	...c24Lessons,
	...c25Lessons
];

export const allLessons: Record<string, LessonNode> = Object.fromEntries(
	all.map((lesson) => [lesson.id, lesson])
);

export function getLesson(id: string): LessonNode | undefined {
	return allLessons[id];
}

export function getLessonsBySection(section: string): LessonNode[] {
	return all.filter((lesson) => lesson.section === section);
}
