// Generated by scripts/snapshot-content.ts — section grouping for the path
// canvas (headings + theme-color order). Edit freely from here on.
import type { SectionMeta } from './types';

export const sectionMeta: SectionMeta[] = [
  {
    "id": "c-1",
    "titleHe": "לפענח את השאלה",
    "titleEn": "Reading the Question",
    "intro": {
      "greeting": "What is the question actually asking?",
      "goal": "לפני שנוגעים בטקסט — לדעת מה נשאל, לאן זה שולח אותנו, ובאיזה אורך לענות."
    }
  },
  {
    "id": "c-2",
    "titleHe": "קריאה אסטרטגית",
    "titleEn": "Strategic Reading"
  },
  {
    "id": "c-3",
    "titleHe": "מגנטים לעין — מספרים ושמות",
    "titleEn": "Numbers & Names"
  },
  {
    "id": "c-4",
    "titleHe": "מגנטים לעין — שלילה, הגבלה וניגוד",
    "titleEn": "Eye Catchers — Negatives, Limiters, Contrast",
    "intro": {
      "greeting": "Three little words that flip an answer",
      "goal": "שלוש משפחות מילים שהופכות תשובה: שלילה (P4), הגבלה (P5) וניגוד (P6). מי שמפספס אותן עונה בדיוק הפוך."
    }
  },
  {
    "id": "c-5",
    "titleHe": "שיטת הרמזור",
    "titleEn": "The Traffic-Light Method"
  },
  {
    "id": "c-6",
    "titleHe": "שאלות פרטים",
    "titleEn": "Detail Questions"
  },
  {
    "id": "c-7",
    "titleHe": "שאלות רב־ברירה",
    "titleEn": "Multiple Choice"
  },
  {
    "id": "c-8",
    "titleHe": "השלמת משפט",
    "titleEn": "Complete the Sentence"
  },
  {
    "id": "c-9",
    "titleHe": "שתי תשובות נכונות",
    "titleEn": "Two Correct Answers"
  },
  {
    "id": "c-10",
    "titleHe": "שאלות התייחסות",
    "titleEn": "Reference Questions"
  },
  {
    "id": "c-11",
    "titleHe": "שאלות הסקה",
    "titleEn": "Inference Questions"
  },
  {
    "id": "c-12",
    "titleHe": "הרעיון המרכזי",
    "titleEn": "Main Idea"
  },
  {
    "id": "c-13",
    "titleHe": "עמדת הכותב",
    "titleEn": "Author's Attitude"
  },
  {
    "id": "c-14",
    "titleHe": "אוצר מילים — חברה",
    "titleEn": "Vocabulary — Social"
  },
  {
    "id": "c-15",
    "titleHe": "אוצר מילים — טכנולוגיה וסביבה",
    "titleEn": "Vocabulary — Tech & Environment"
  },
  {
    "id": "c-16",
    "titleHe": "מילים לכתיבה",
    "titleEn": "Words for Writing"
  },
  {
    "id": "c-17",
    "titleHe": "משפטים שעובדים",
    "titleEn": "Sentences That Work"
  },
  {
    "id": "c-18",
    "titleHe": "מילות קישור",
    "titleEn": "Connectors — Error Clinic"
  },
  {
    "id": "c-19",
    "titleHe": "ניהול זמן",
    "titleEn": "Time Management"
  },
  {
    "id": "c-20",
    "titleHe": "אתגר מתוזמן",
    "titleEn": "Timed Challenge"
  },
  {
    "id": "c-21",
    "titleHe": "שאלות כן/לא",
    "titleEn": "Yes / No Questions"
  },
  {
    "id": "c-22",
    "titleHe": "נימוק, הסבר ודוגמה",
    "titleEn": "Reason · Explanation · Example"
  },
  {
    "id": "c-23",
    "titleHe": "בנק דוגמאות למבחן",
    "titleEn": "Example Bank for the Exam"
  },
  {
    "id": "c-24",
    "titleHe": "סימולציה מלאה",
    "titleEn": "Full Simulation"
  },
  {
    "id": "c-25",
    "titleHe": "ניתוח שגיאות מסכם",
    "titleEn": "Error Analysis"
  }
];
