// The Module C source texts, verbatim from the teacher programme
// (docs/module c/program, L1..L24). Every section pulls its passages from
// here — the same text is deliberately reused across sections (mark it, then
// answer questions on it, then meet it again under a clock), so the student's
// attention goes to the new skill and not to new content.

export const swim = `LEARNING TO SWIM AS AN ADULT
I  Learning to swim as an adult is more common than many people think. According to a recent survey, over 30% of adults in large cities cannot swim. Many of them feel embarrassed about this and never try to learn. However, experts say it is never too late.
II  One study found that adults who learned to swim later in life often became stronger swimmers than those who learned as children. "Adults understand what the teacher explains and can correct their mistakes more quickly," says Dr. Anna Klein, a sports psychologist at the University of Oslo. "They are also not afraid to ask questions."
III  Adult swimming classes are now available in most cities. Some programs meet only once a week, while others offer three sessions a week. According to instructors, adults who practice regularly usually make good progress in less than two months.`;

export const languageOnline = `LEARNING A LANGUAGE ONLINE
Over the past ten years, online language learning has become very popular. According to a recent study, more than 500 million people worldwide now use language apps on their phones. Most of these learners are adults who want to improve their language skills for work or travel. However, not all apps are equally effective. Language experts say that apps work best when students also practice speaking with real people. "No app can replace a real conversation," says Dr. Yuki Tanaka, a language researcher at Tokyo University.`;

export const cityGarden = `THE CITY GARDEN PROJECT
I  Five years ago, the streets of Greenville had almost no plants or trees. The air was polluted, and most residents felt that the city was an unpleasant place to live. A local charity decided to change this. They planted over 2,000 trees and created 15 community gardens across the city. Today, Greenville looks very different.
II  The person behind this change is Dr. Maria Santos, a professor at Greenville University. "We wanted to show that any city can become greener in less than ten years," she explains. Her team worked with more than 300 volunteers from the local community. The volunteers spent an average of three hours a week working in the gardens.
III  The results were surprising. According to the charity, 85% of Greenville residents now say the city is a better place to live. Dr. Santos's colleague, Professor James Wu, found that stress levels among residents had fallen by 40%. "When people have access to green spaces, they feel calmer and happier," he says. The project now receives visits from city planners from over 50 countries who want to learn from Greenville's success.`;

/** Paragraph I of THE CITY GARDEN PROJECT — the short marking passage. */
export const cityGardenI = `Five years ago, the streets of Greenville had almost no plants or trees. The air was polluted, and most residents felt that the city was an unpleasant place to live. A local charity decided to change this. They planted over 2,000 trees and created 15 community gardens across the city.`;

/** Paragraphs II–III of THE CITY GARDEN PROJECT — the medium marking passage. */
export const cityGardenIII = `The person behind this change is Dr. Maria Santos, a professor at Greenville University. Her team worked with more than 300 volunteers from the local community. The volunteers spent an average of three hours a week working in the gardens. According to the charity, 85% of Greenville residents now say the city is a better place to live. Professor James Wu found that stress levels among residents had fallen by 40%.`;

export const sportForAll = `SPORT FOR ALL
A new community sports programme in the city of Portland has helped over 4,000 residents become more active over the past two years. The programme offers free fitness classes three times a week in 12 different neighbourhoods. According to Dr. Laura Kim, who runs the programme, the idea is simple. "We bring the sport to the people, not the people to the sport," she says. "Most people want to be active — they just need the opportunity." Professor Marcus Allen of Portland State University found that participants in the programme were 60% less likely to suffer from stress-related health problems.`;

export const givingTime = `GIVING TIME, GAINING HAPPINESS
I  Every year, millions of young people around the world choose to volunteer — to give their time to help others without payment. A study from a research institute found that young people who volunteer for at least two hours a week are 60% more likely to describe themselves as happy. Researchers were surprised. They had expected that money and success — not helping others — would be the main reason for happiness among teenagers.
II  The benefits of volunteering go beyond simple happiness. Dr. Sarah Okafor, a researcher at a European university, studied the effects of volunteering on mental health for ten years. She found that teenagers who volunteer feel less stressed and sleep better than those who do not. However, not all types of volunteering produce the same results. According to Okafor, the most effective programmes bring young people face to face with the people they help — not online activities.
III  Results from 12 countries show that the benefits of volunteering are not limited to the volunteers themselves. Schools that introduced volunteering programmes found that students became more responsible and more focused in class. Professor David Mills of an Australian university argues that helping others teaches young people skills that no classroom can ever replace. "When you help someone," he says, "you also help yourself."`;

/** Paragraph II of GIVING TIME — the negatives/limiters marking passage. */
export const givingTimeII = `The benefits of volunteering go beyond simple happiness. Dr. Sarah Okafor studied the effects of volunteering on mental health for ten years. She found that teenagers who volunteer feel less stressed and sleep better than those who do not. However, not all types of volunteering produce the same results. According to Okafor, the most effective programmes bring young people face to face with the people they help — not online activities.`;

export const sleepQuestion = `THE SLEEP QUESTION
Most people know that sleep is important for health. However, a new study from the National Sleep Research Centre shows that the quality of sleep matters more than the quantity. Researchers found that people who sleep for six hours of deep, uninterrupted sleep feel more rested than those who sleep for nine hours but wake up several times during the night. Dr. Claire Webb, who led the study, says: "The most important factor is not the number of hours, but the depth of the sleep." She recommends that people avoid screens for at least one hour before going to bed.`;

export const boredomStudy = `THE BOREDOM STUDY
Researchers at a British university recently published a surprising study about boredom. The study found that people who spent ten minutes doing a boring task before a creative activity produced twice as many creative ideas as those who did not do a boring task first. Dr. Sandi Mann, who led the research, says: "Boredom allows the brain to wander freely. This is when most creative ideas appear." However, she warns that not all types of boredom have the same effect. Only passive boredom — such as watching a blank screen — produced this result. Active boredom, such as a sport or a walk, did not have the same effect.`;

export const sleepDebate = `THE SLEEP DEBATE
Scientists have been debating the question of how much sleep teenagers need for many years. A new study by Dr. Fatima Hasan at Cairo University examined 3,000 high school students over four years. She found that students who slept for nine hours performed significantly better in exams than those who slept for six hours or less. However, not all experts agree. Professor Yuki Tanaka of Tokyo University argues that the quality of sleep is more important than the quantity. "A teenager who sleeps for seven hours without interruption benefits more than one who sleeps for ten hours but wakes frequently," he says.`;

export const screenTime = `THE SCREEN TIME DEBATE
Parents and teachers have been worried about screen time for many years. Most experts agree that too much screen time can harm children's sleep and social skills. However, a new study from Stanford University suggests that screen time is not always harmful. Dr. Emily Park, who led the study, examined 4,500 children aged between 8 and 12. She found that children who spent up to one hour a day on creative screen activities — such as drawing or coding programmes — showed better problem-solving skills than those who spent no time on screens.`;

export const jobRevolution = `THE JOB REVOLUTION
I  The world of work is changing faster than ever before. According to a recent report, over 85 million jobs will disappear in the next ten years because of automation and artificial intelligence. However, the same report predicts that 97 million new jobs will also appear. The problem is that many workers are not prepared for these new kinds of jobs.
II  Emma Clarke, a researcher at the Digital Skills Institute in London, believes that the solution lies in education. "Most schools still teach students skills for the jobs of yesterday, not the jobs of tomorrow," she says. According to Clarke, the three most important skills for the future are critical thinking, digital literacy, and communication.
III  Some governments have already begun to act. In 2023, the government of Singapore introduced a new programme that gives every adult worker 500 dollars a year to spend on training courses. More than 300,000 workers have already taken advantage of this programme. Professor Lee Min, an economist at National University of Singapore, says the results are encouraging: workers who complete at least one course a year are 35% less likely to lose their jobs.`;

export const waterCrisis = `THE WATER CRISIS
Access to clean water is one of the most serious problems facing the world today. According to Dr. Layla Ahmed of the Global Water Institute, over 2 billion people currently have no access to safe drinking water. "This is not only a health crisis — it is also an economic one," she explains. "Countries that cannot provide clean water lose an estimated 260 billion dollars every year in lost productivity." Dr. Ahmed argues that the most effective solution is to invest in local water treatment systems rather than relying on international aid.`;

export const readingDebate = `THE READING DEBATE
Studies show that most young people today read less than they did 20 years ago. Dr. Yael Cohen of Tel Aviv University examined reading habits among 6,000 teenagers across five countries. She found that teenagers who read for at least 30 minutes a day had better vocabulary and stronger empathy skills than those who did not. However, Dr. Cohen found that the format of reading did not matter — reading on a screen was as effective as reading a printed book. Professor Sam Lee of Oxford University argues that schools should make reading a daily activity in all subjects, not only in language classes.`;

export const exerciseMyth = `THE EXERCISE MYTH
I  Most people believe that to get fit, they need to exercise for at least 30 minutes every day. However, new research suggests this idea may be wrong. According to a study published in the Journal of Sports Science, short bursts of intense exercise — as little as seven minutes a day — can be just as effective as longer workouts. This finding challenges everything most fitness experts have said for decades.
II  Dr. Jennifer Cho, a sports scientist at Yonsei University in South Korea, tested two groups of volunteers for 12 weeks. The first group exercised for 30 minutes every day. The second group did seven minutes of intense exercise three times a day. At the end, Dr. Cho found that both groups had similar improvements. However, the second group reported feeling more energetic and less stressed.
III  Not all scientists agree with these findings. Professor Robert Walsh of Oxford University argues that the research has serious limitations. "The study only looked at healthy young adults," he says. "We cannot apply these results to older people or those with health problems." He also points out that most people cannot maintain these routines for more than a few weeks.`;

export const forestExperiment = `THE FOREST EXPERIMENT
Scientists at Uppsala University in Sweden have been studying the effects of spending time in forests on mental health. In their latest experiment, they asked 200 volunteers to walk in a forest for one hour every day for two weeks. They found that stress levels fell by an average of 35% among participants. However, the scientists were careful to note that not all of these improvements were caused by the forest itself. "Some of the benefit may have come simply from the exercise of walking," explains Professor Anna Lindgren, who led the research. "We plan to repeat the experiment with a group that walks in a city — not a forest — to find out if the results are similar."`;

export const memoryStudy = `THE MEMORY STUDY
Scientists at Cambridge University have discovered that people remember information better when they write it by hand than when they type it. In a study of 150 university students, those who took notes by hand scored 25% higher in memory tests than those who typed. The researchers explain that handwriting requires people to process and rephrase the information, rather than simply copying it. However, not all the students who handwrote scored higher. Those who wrote very slowly and could not keep up with the information performed no better than those who typed.`;

export const lastForests = `THE LAST FORESTS
I  Every year, the world loses approximately 15 billion trees. This destruction is happening faster than ever before, and scientists are deeply worried. Forests cover less than 30% of the earth's surface today, compared to 50% just 100 years ago. "The situation is critical," says Dr. Amara Diallo, director of the Global Forest Watch organisation. "Once they are gone, they cannot easily be replaced."
II  The causes of deforestation are well known. In most parts of the world, forests are cut down to make space for farming. This is particularly true in South America, where large areas of rainforest are destroyed every year to create farmland. Climate change makes the problem worse by causing longer and more severe droughts, which weaken trees and make them more likely to burn in forest fires.
III  However, there are reasons to be hopeful. Several countries have recently introduced strict laws to protect their forests. Professor Lena Berg of Stockholm University reports that in Scandinavia, the number of trees has actually increased by 40% over the past 50 years. "It is possible to stop deforestation," she says, "but it requires both governments and individuals to make difficult choices."`;

export const plasticProblem = `THE PLASTIC PROBLEM
Scientists estimate that 8 million tonnes of plastic enter the world's oceans every year. This plastic comes from many sources, including industrial waste, household rubbish, and single-use packaging. Most of this plastic does not biodegrade — it simply breaks into smaller and smaller pieces called microplastics. Dr. Rania Khalil of the Mediterranean Environmental Institute warns that microplastics have been found in fish, drinking water, and even human blood. "The full effects on human health are still unknown," she says, "but we cannot afford to wait for more evidence before taking action."`;

export const cleanEnergy = `THE CLEAN ENERGY TRANSITION
The world is moving towards clean energy faster than most experts predicted. Fortunately, the cost of solar power has fallen by more than 80% over the past ten years, making it cheaper than coal in most countries. However, scientists warn that the transition is not happening fast enough. "We need to triple the speed of the transition if we are to meet climate targets," says Dr. Sofia Reyes of the International Energy Agency. "The technology exists. The only question is whether governments have the political will to use it."`;
